-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity GaussianFilter is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 6;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of GaussianFilter is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "GaussianFilter_GaussianFilter,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z007s-clg400-1,HLS_INPUT_CLOCK=8.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.450000,HLS_SYN_LAT=5,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=469,HLS_SYN_LUT=959,HLS_VERSION=2025_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_lv16_A4 : STD_LOGIC_VECTOR (15 downto 0) := "0000000010100100";
    constant ap_const_lv16_AE : STD_LOGIC_VECTOR (15 downto 0) := "0000000010101110";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv16_97 : STD_LOGIC_VECTOR (15 downto 0) := "0000000010010111";
    constant ap_const_lv16_AA : STD_LOGIC_VECTOR (15 downto 0) := "0000000010101010";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv16_B1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000010110001";

attribute shreg_extract : string;
    signal ap_rst_reg_2 : STD_LOGIC := '1';
attribute shreg_extract of ap_rst_reg_2 : signal is "no";
    signal ap_rst_reg_1 : STD_LOGIC := '1';
attribute shreg_extract of ap_rst_reg_1 : signal is "no";
    signal ap_rst_n_inv : STD_LOGIC := '1';
attribute shreg_extract of ap_rst_n_inv : signal is "no";
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_continue : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal data_in_0 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_in_1 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_in_2 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_in_3 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_in_4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_3 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_3 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_3 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_3 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_3 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_return : STD_LOGIC_VECTOR (31 downto 0);
    signal p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_3_load_reg_934 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_1_load_reg_939 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_1_load_reg_944 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_2_load_reg_965 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_2_load_reg_971 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_3_load_reg_977 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_2_load_reg_983 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_in_4_read_reg_1034 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal data_in_0_read_reg_1040 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_in_3_read_reg_1061 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal data_in_1_read_reg_1067 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_837_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_829_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_845_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln92_4_fu_724_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln92_4_reg_1118 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal add_ln92_9_fu_748_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln92_9_reg_1123 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln92_15_fu_760_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln92_15_reg_1128 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln92_21_fu_785_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal add_ln92_21_reg_1133 : STD_LOGIC_VECTOR (18 downto 0);
    signal mul_ln46_10_fu_331_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln46_10_fu_331_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln46_10_fu_331_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln46_12_fu_344_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln46_12_fu_344_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln46_12_fu_344_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_10_fu_354_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_11_fu_365_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln46_51_fu_361_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln46_52_fu_372_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln46_5_fu_376_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln46_fu_431_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln46_fu_431_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln46_fu_431_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_fu_441_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_1_fu_453_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln46_2_fu_449_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln46_6_fu_461_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln46_fu_465_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln46_5_fu_478_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln46_5_fu_478_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln46_5_fu_478_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln46_14_fu_491_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln46_14_fu_491_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln46_14_fu_491_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_12_fu_501_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_13_fu_513_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln46_53_fu_509_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln46_54_fu_521_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln46_6_fu_525_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_14_fu_535_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_15_fu_546_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln46_55_fu_542_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln46_56_fu_553_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln46_7_fu_557_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_2_fu_576_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_3_fu_587_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln46_10_fu_583_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln46_18_fu_594_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln46_1_fu_598_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_4_fu_608_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_5_fu_619_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln46_30_fu_615_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln46_38_fu_626_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln46_2_fu_630_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_6_fu_640_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_7_fu_652_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln46_42_fu_648_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln46_46_fu_660_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln46_3_fu_664_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_8_fu_674_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_9_fu_685_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln46_49_fu_681_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln46_50_fu_692_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln46_4_fu_696_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_889_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln46_11_fu_636_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln92_1_fu_706_p2 : STD_LOGIC_VECTOR (16 downto 0);
    attribute use_dsp48 : string;
    attribute use_dsp48 of add_ln92_1_fu_706_p2 : signal is "no";
    signal grp_fu_862_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln46_31_fu_702_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln92_3_fu_715_p2 : STD_LOGIC_VECTOR (16 downto 0);
    attribute use_dsp48 of add_ln92_3_fu_715_p2 : signal is "no";
    signal zext_ln92_2_fu_720_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln92_1_fu_711_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_853_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln46_7_fu_604_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln92_6_fu_730_p2 : STD_LOGIC_VECTOR (16 downto 0);
    attribute use_dsp48 of add_ln92_6_fu_730_p2 : signal is "no";
    signal grp_fu_880_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln46_19_fu_670_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln92_8_fu_739_p2 : STD_LOGIC_VECTOR (16 downto 0);
    attribute use_dsp48 of add_ln92_8_fu_739_p2 : signal is "no";
    signal zext_ln92_5_fu_744_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln92_4_fu_735_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_871_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_898_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln92_9_fu_757_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln92_8_fu_754_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_907_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_925_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_916_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln92_13_fu_772_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln92_12_fu_769_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln92_20_fu_775_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln92_14_fu_781_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal zext_ln92_11_fu_766_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal zext_ln92_6_fu_794_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal zext_ln92_3_fu_791_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal add_ln92_10_fu_797_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal zext_ln92_15_fu_810_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal zext_ln92_10_fu_807_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal add_ln92_22_fu_813_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal zext_ln92_7_fu_803_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal add_ln92_23_fu_819_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal grp_fu_829_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_829_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_829_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_837_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_837_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_837_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_845_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_845_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_845_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_853_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_853_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_853_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_862_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_862_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_862_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_871_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_871_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_880_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_880_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_880_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_889_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_889_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_889_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_898_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_898_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_907_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_907_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_916_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_916_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_916_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_925_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_925_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_925_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_829_ce : STD_LOGIC;
    signal grp_fu_837_ce : STD_LOGIC;
    signal grp_fu_845_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal grp_fu_829_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_829_p20 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_837_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_837_p20 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_845_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_845_p20 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_853_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_853_p20 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_862_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_862_p20 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_871_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_880_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_880_p20 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_889_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_889_p20 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_898_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_907_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_916_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_916_p20 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_925_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_925_p20 : STD_LOGIC_VECTOR (16 downto 0);
    signal mul_ln46_10_fu_331_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln46_12_fu_344_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln46_14_fu_491_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln46_5_fu_478_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln46_fu_431_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component GaussianFilter_mul_8ns_9ns_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (8 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component GaussianFilter_mac_muladd_8ns_8ns_16ns_17_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (16 downto 0) );
    end component;


    component GaussianFilter_mac_muladd_8ns_8ns_17ns_17_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (16 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (16 downto 0) );
    end component;


    component GaussianFilter_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_continue : OUT STD_LOGIC;
        ap_idle : IN STD_LOGIC;
        ap_return : IN STD_LOGIC_VECTOR (31 downto 0);
        data_in_0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        data_in_1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        data_in_2 : OUT STD_LOGIC_VECTOR (7 downto 0);
        data_in_3 : OUT STD_LOGIC_VECTOR (7 downto 0);
        data_in_4 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    control_s_axi_U : component GaussianFilter_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_continue => ap_continue,
        ap_idle => ap_idle,
        ap_return => ap_return,
        data_in_0 => data_in_0,
        data_in_1 => data_in_1,
        data_in_2 => data_in_2,
        data_in_3 => data_in_3,
        data_in_4 => data_in_4);

    mul_8ns_9ns_16_1_1_U1 : component GaussianFilter_mul_8ns_9ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 9,
        dout_WIDTH => 16)
    port map (
        din0 => mul_ln46_10_fu_331_p0,
        din1 => mul_ln46_10_fu_331_p1,
        dout => mul_ln46_10_fu_331_p2);

    mul_8ns_9ns_16_1_1_U2 : component GaussianFilter_mul_8ns_9ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 9,
        dout_WIDTH => 16)
    port map (
        din0 => mul_ln46_12_fu_344_p0,
        din1 => mul_ln46_12_fu_344_p1,
        dout => mul_ln46_12_fu_344_p2);

    mul_8ns_9ns_16_1_1_U3 : component GaussianFilter_mul_8ns_9ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 9,
        dout_WIDTH => 16)
    port map (
        din0 => mul_ln46_fu_431_p0,
        din1 => mul_ln46_fu_431_p1,
        dout => mul_ln46_fu_431_p2);

    mul_8ns_9ns_16_1_1_U4 : component GaussianFilter_mul_8ns_9ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 9,
        dout_WIDTH => 16)
    port map (
        din0 => mul_ln46_5_fu_478_p0,
        din1 => mul_ln46_5_fu_478_p1,
        dout => mul_ln46_5_fu_478_p2);

    mul_8ns_9ns_16_1_1_U5 : component GaussianFilter_mul_8ns_9ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 9,
        dout_WIDTH => 16)
    port map (
        din0 => mul_ln46_14_fu_491_p0,
        din1 => mul_ln46_14_fu_491_p1,
        dout => mul_ln46_14_fu_491_p2);

    mac_muladd_8ns_8ns_16ns_17_4_1_U6 : component GaussianFilter_mac_muladd_8ns_8ns_16ns_17_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_829_p0,
        din1 => grp_fu_829_p1,
        din2 => grp_fu_829_p2,
        ce => grp_fu_829_ce,
        dout => grp_fu_829_p3);

    mac_muladd_8ns_8ns_16ns_17_4_1_U7 : component GaussianFilter_mac_muladd_8ns_8ns_16ns_17_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_837_p0,
        din1 => grp_fu_837_p1,
        din2 => grp_fu_837_p2,
        ce => grp_fu_837_ce,
        dout => grp_fu_837_p3);

    mac_muladd_8ns_8ns_16ns_17_4_1_U8 : component GaussianFilter_mac_muladd_8ns_8ns_16ns_17_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_845_p0,
        din1 => grp_fu_845_p1,
        din2 => grp_fu_845_p2,
        ce => grp_fu_845_ce,
        dout => grp_fu_845_p3);

    mac_muladd_8ns_8ns_16ns_17_4_1_U9 : component GaussianFilter_mac_muladd_8ns_8ns_16ns_17_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_853_p0,
        din1 => grp_fu_853_p1,
        din2 => grp_fu_853_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_853_p3);

    mac_muladd_8ns_8ns_16ns_17_4_1_U10 : component GaussianFilter_mac_muladd_8ns_8ns_16ns_17_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_862_p0,
        din1 => grp_fu_862_p1,
        din2 => grp_fu_862_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_862_p3);

    mac_muladd_8ns_8ns_17ns_17_4_1_U11 : component GaussianFilter_mac_muladd_8ns_8ns_17ns_17_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 17,
        dout_WIDTH => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_871_p0,
        din1 => grp_fu_871_p1,
        din2 => grp_fu_837_p3,
        ce => ap_const_logic_1,
        dout => grp_fu_871_p3);

    mac_muladd_8ns_8ns_16ns_17_4_1_U12 : component GaussianFilter_mac_muladd_8ns_8ns_16ns_17_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_880_p0,
        din1 => grp_fu_880_p1,
        din2 => grp_fu_880_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_880_p3);

    mac_muladd_8ns_8ns_16ns_17_4_1_U13 : component GaussianFilter_mac_muladd_8ns_8ns_16ns_17_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_889_p0,
        din1 => grp_fu_889_p1,
        din2 => grp_fu_889_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_889_p3);

    mac_muladd_8ns_8ns_17ns_17_4_1_U14 : component GaussianFilter_mac_muladd_8ns_8ns_17ns_17_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 17,
        dout_WIDTH => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_898_p0,
        din1 => grp_fu_898_p1,
        din2 => grp_fu_829_p3,
        ce => ap_const_logic_1,
        dout => grp_fu_898_p3);

    mac_muladd_8ns_8ns_17ns_17_4_1_U15 : component GaussianFilter_mac_muladd_8ns_8ns_17ns_17_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 17,
        dout_WIDTH => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_907_p0,
        din1 => grp_fu_907_p1,
        din2 => grp_fu_845_p3,
        ce => ap_const_logic_1,
        dout => grp_fu_907_p3);

    mac_muladd_8ns_8ns_16ns_17_4_1_U16 : component GaussianFilter_mac_muladd_8ns_8ns_16ns_17_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_916_p0,
        din1 => grp_fu_916_p1,
        din2 => grp_fu_916_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_916_p3);

    mac_muladd_8ns_8ns_16ns_17_4_1_U17 : component GaussianFilter_mac_muladd_8ns_8ns_16ns_17_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_925_p0,
        din1 => grp_fu_925_p1,
        din2 => grp_fu_925_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_925_p3);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_rst_n_inv_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_rst_n_inv <= ap_rst_reg_1;
        end if;
    end process;

    ap_rst_reg_1_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_rst_reg_1 <= ap_rst_reg_2;
        end if;
    end process;

    ap_rst_reg_2_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
                        ap_rst_reg_2 <= not(ap_rst_n);
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                add_ln92_15_reg_1128 <= add_ln92_15_fu_760_p2;
                add_ln92_21_reg_1133 <= add_ln92_21_fu_785_p2;
                add_ln92_4_reg_1118 <= add_ln92_4_fu_724_p2;
                add_ln92_9_reg_1123 <= add_ln92_9_fu_748_p2;
                p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_3 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_2_load_reg_971;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                data_in_0_read_reg_1040 <= data_in_0;
                data_in_4_read_reg_1034 <= data_in_4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                data_in_1_read_reg_1067 <= data_in_1;
                data_in_3_read_reg_1061 <= data_in_3;
                p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_0 <= data_in_0_read_reg_1040;
                p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_1 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_0;
                p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_0 <= data_in_1;
                p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_0 <= data_in_3;
                p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_0 <= data_in_4_read_reg_1034;
                p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_1 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_2 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_1;
                p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_2_load_reg_965 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_2;
                p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_3 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_2;
                p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_1 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_0;
                p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_2 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_1;
                p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_2_load_reg_971 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_2;
                p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_0 <= data_in_2;
                p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_2 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_1_load_reg_944;
                p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_3 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_2;
                p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_3_load_reg_977 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_3;
                p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_2 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_1;
                p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_2_load_reg_983 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_2;
                p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_3 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_1 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_0;
                p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_1_load_reg_939 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_1;
                p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_2 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_1;
                p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_3 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_2;
                p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_3_load_reg_934 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_3;
                p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_1 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_0;
                p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_1_load_reg_944 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    add_ln46_1_fu_598_p2 <= std_logic_vector(unsigned(zext_ln46_10_fu_583_p1) + unsigned(zext_ln46_18_fu_594_p1));
    add_ln46_2_fu_630_p2 <= std_logic_vector(unsigned(zext_ln46_30_fu_615_p1) + unsigned(zext_ln46_38_fu_626_p1));
    add_ln46_3_fu_664_p2 <= std_logic_vector(unsigned(zext_ln46_42_fu_648_p1) + unsigned(zext_ln46_46_fu_660_p1));
    add_ln46_4_fu_696_p2 <= std_logic_vector(unsigned(zext_ln46_49_fu_681_p1) + unsigned(zext_ln46_50_fu_692_p1));
    add_ln46_5_fu_376_p2 <= std_logic_vector(unsigned(zext_ln46_51_fu_361_p1) + unsigned(zext_ln46_52_fu_372_p1));
    add_ln46_6_fu_525_p2 <= std_logic_vector(unsigned(zext_ln46_53_fu_509_p1) + unsigned(zext_ln46_54_fu_521_p1));
    add_ln46_7_fu_557_p2 <= std_logic_vector(unsigned(zext_ln46_55_fu_542_p1) + unsigned(zext_ln46_56_fu_553_p1));
    add_ln46_fu_465_p2 <= std_logic_vector(unsigned(zext_ln46_2_fu_449_p1) + unsigned(zext_ln46_6_fu_461_p1));
    add_ln92_10_fu_797_p2 <= std_logic_vector(unsigned(zext_ln92_6_fu_794_p1) + unsigned(zext_ln92_3_fu_791_p1));
    add_ln92_15_fu_760_p2 <= std_logic_vector(unsigned(zext_ln92_9_fu_757_p1) + unsigned(zext_ln92_8_fu_754_p1));
    add_ln92_1_fu_706_p2 <= std_logic_vector(unsigned(grp_fu_889_p3) + unsigned(zext_ln46_11_fu_636_p1));
    add_ln92_20_fu_775_p2 <= std_logic_vector(unsigned(zext_ln92_13_fu_772_p1) + unsigned(zext_ln92_12_fu_769_p1));
    add_ln92_21_fu_785_p2 <= std_logic_vector(unsigned(zext_ln92_14_fu_781_p1) + unsigned(zext_ln92_11_fu_766_p1));
    add_ln92_22_fu_813_p2 <= std_logic_vector(unsigned(zext_ln92_15_fu_810_p1) + unsigned(zext_ln92_10_fu_807_p1));
    add_ln92_23_fu_819_p2 <= std_logic_vector(unsigned(add_ln92_22_fu_813_p2) + unsigned(zext_ln92_7_fu_803_p1));
    add_ln92_3_fu_715_p2 <= std_logic_vector(unsigned(grp_fu_862_p3) + unsigned(zext_ln46_31_fu_702_p1));
    add_ln92_4_fu_724_p2 <= std_logic_vector(unsigned(zext_ln92_2_fu_720_p1) + unsigned(zext_ln92_1_fu_711_p1));
    add_ln92_6_fu_730_p2 <= std_logic_vector(unsigned(grp_fu_853_p3) + unsigned(zext_ln46_7_fu_604_p1));
    add_ln92_8_fu_739_p2 <= std_logic_vector(unsigned(grp_fu_880_p3) + unsigned(zext_ln46_19_fu_670_p1));
    add_ln92_9_fu_748_p2 <= std_logic_vector(unsigned(zext_ln92_5_fu_744_p1) + unsigned(zext_ln92_4_fu_735_p1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln92_23_fu_819_p2),32));

    grp_fu_829_ce_assign_proc : process(ap_CS_fsm_state1, ap_block_state1, ap_CS_fsm_state5, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5) or ((ap_const_boolean_1 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            grp_fu_829_ce <= ap_const_logic_0;
        else 
            grp_fu_829_ce <= ap_const_logic_1;
        end if; 
    end process;

    grp_fu_829_p0 <= grp_fu_829_p00(8 - 1 downto 0);
    grp_fu_829_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_0),16));
    grp_fu_829_p1 <= ap_const_lv16_AE(8 - 1 downto 0);
    grp_fu_829_p2 <= grp_fu_829_p20(16 - 1 downto 0);
    grp_fu_829_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln46_5_fu_376_p2),17));

    grp_fu_837_ce_assign_proc : process(ap_CS_fsm_state1, ap_block_state1, ap_CS_fsm_state5, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5) or ((ap_const_boolean_1 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            grp_fu_837_ce <= ap_const_logic_0;
        else 
            grp_fu_837_ce <= ap_const_logic_1;
        end if; 
    end process;

    grp_fu_837_p0 <= grp_fu_837_p00(8 - 1 downto 0);
    grp_fu_837_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_2),16));
    grp_fu_837_p1 <= ap_const_lv16_AE(8 - 1 downto 0);
    grp_fu_837_p2 <= grp_fu_837_p20(16 - 1 downto 0);
    grp_fu_837_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln46_10_fu_331_p2),17));

    grp_fu_845_ce_assign_proc : process(ap_CS_fsm_state1, ap_block_state1, ap_CS_fsm_state5, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5) or ((ap_const_boolean_1 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            grp_fu_845_ce <= ap_const_logic_0;
        else 
            grp_fu_845_ce <= ap_const_logic_1;
        end if; 
    end process;

    grp_fu_845_p0 <= grp_fu_845_p00(8 - 1 downto 0);
    grp_fu_845_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_0),16));
    grp_fu_845_p1 <= ap_const_lv16_AA(8 - 1 downto 0);
    grp_fu_845_p2 <= grp_fu_845_p20(16 - 1 downto 0);
    grp_fu_845_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln46_12_fu_344_p2),17));
    grp_fu_853_p0 <= grp_fu_853_p00(8 - 1 downto 0);
    grp_fu_853_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_1),16));
    grp_fu_853_p1 <= ap_const_lv16_A4(8 - 1 downto 0);
    grp_fu_853_p2 <= grp_fu_853_p20(16 - 1 downto 0);
    grp_fu_853_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln46_fu_465_p2),17));
    grp_fu_862_p0 <= grp_fu_862_p00(8 - 1 downto 0);
    grp_fu_862_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_3),16));
    grp_fu_862_p1 <= ap_const_lv16_97(8 - 1 downto 0);
    grp_fu_862_p2 <= grp_fu_862_p20(16 - 1 downto 0);
    grp_fu_862_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln46_14_fu_491_p2),17));
    grp_fu_871_p0 <= grp_fu_871_p00(8 - 1 downto 0);
    grp_fu_871_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_0),16));
    grp_fu_871_p1 <= ap_const_lv16_AA(8 - 1 downto 0);
    grp_fu_880_p0 <= grp_fu_880_p00(8 - 1 downto 0);
    grp_fu_880_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_1),16));
    grp_fu_880_p1 <= ap_const_lv16_AE(8 - 1 downto 0);
    grp_fu_880_p2 <= grp_fu_880_p20(16 - 1 downto 0);
    grp_fu_880_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln46_5_fu_478_p2),17));
    grp_fu_889_p0 <= grp_fu_889_p00(8 - 1 downto 0);
    grp_fu_889_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(data_in_2),16));
    grp_fu_889_p1 <= ap_const_lv16_A4(8 - 1 downto 0);
    grp_fu_889_p2 <= grp_fu_889_p20(16 - 1 downto 0);
    grp_fu_889_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln46_fu_431_p2),17));
    grp_fu_898_p0 <= grp_fu_898_p00(8 - 1 downto 0);
    grp_fu_898_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_1_load_reg_939),16));
    grp_fu_898_p1 <= ap_const_lv16_B1(8 - 1 downto 0);
    grp_fu_907_p0 <= grp_fu_907_p00(8 - 1 downto 0);
    grp_fu_907_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_2),16));
    grp_fu_907_p1 <= ap_const_lv16_AA(8 - 1 downto 0);
    grp_fu_916_p0 <= grp_fu_916_p00(8 - 1 downto 0);
    grp_fu_916_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_1),16));
    grp_fu_916_p1 <= ap_const_lv16_A4(8 - 1 downto 0);
    grp_fu_916_p2 <= grp_fu_916_p20(16 - 1 downto 0);
    grp_fu_916_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln46_6_fu_525_p2),17));
    grp_fu_925_p0 <= grp_fu_925_p00(8 - 1 downto 0);
    grp_fu_925_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_3),16));
    grp_fu_925_p1 <= ap_const_lv16_97(8 - 1 downto 0);
    grp_fu_925_p2 <= grp_fu_925_p20(16 - 1 downto 0);
    grp_fu_925_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln46_7_fu_557_p2),17));
    mul_ln46_10_fu_331_p0 <= mul_ln46_10_fu_331_p00(8 - 1 downto 0);
    mul_ln46_10_fu_331_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_3_load_reg_934),16));
    mul_ln46_10_fu_331_p1 <= ap_const_lv16_A4(9 - 1 downto 0);
    mul_ln46_12_fu_344_p0 <= mul_ln46_12_fu_344_p00(8 - 1 downto 0);
    mul_ln46_12_fu_344_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_1_load_reg_944),16));
    mul_ln46_12_fu_344_p1 <= ap_const_lv16_AE(9 - 1 downto 0);
    mul_ln46_14_fu_491_p0 <= mul_ln46_14_fu_491_p00(8 - 1 downto 0);
    mul_ln46_14_fu_491_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(data_in_4_read_reg_1034),16));
    mul_ln46_14_fu_491_p1 <= ap_const_lv16_97(9 - 1 downto 0);
    mul_ln46_5_fu_478_p0 <= mul_ln46_5_fu_478_p00(8 - 1 downto 0);
    mul_ln46_5_fu_478_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_2_load_reg_971),16));
    mul_ln46_5_fu_478_p1 <= ap_const_lv16_AA(9 - 1 downto 0);
    mul_ln46_fu_431_p0 <= mul_ln46_fu_431_p00(8 - 1 downto 0);
    mul_ln46_fu_431_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(data_in_0_read_reg_1040),16));
    mul_ln46_fu_431_p1 <= ap_const_lv16_97(9 - 1 downto 0);
    tmp_10_fu_354_p3 <= (p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_3_load_reg_977 & ap_const_lv7_0);
    tmp_11_fu_365_p3 <= (p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_3_load_reg_977 & ap_const_lv5_0);
    tmp_12_fu_501_p3 <= (p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_0 & ap_const_lv7_0);
    tmp_13_fu_513_p3 <= (p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_0 & ap_const_lv5_0);
    tmp_14_fu_535_p3 <= (p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_2_load_reg_983 & ap_const_lv7_0);
    tmp_15_fu_546_p3 <= (p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_2_load_reg_983 & ap_const_lv5_0);
    tmp_1_fu_453_p3 <= (p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_0 & ap_const_lv5_0);
    tmp_2_fu_576_p3 <= (p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_2_load_reg_965 & ap_const_lv7_0);
    tmp_3_fu_587_p3 <= (p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_2_load_reg_965 & ap_const_lv5_0);
    tmp_4_fu_608_p3 <= (data_in_1_read_reg_1067 & ap_const_lv7_0);
    tmp_5_fu_619_p3 <= (data_in_1_read_reg_1067 & ap_const_lv5_0);
    tmp_6_fu_640_p3 <= (p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_3 & ap_const_lv7_0);
    tmp_7_fu_652_p3 <= (p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_3 & ap_const_lv5_0);
    tmp_8_fu_674_p3 <= (data_in_3_read_reg_1061 & ap_const_lv7_0);
    tmp_9_fu_685_p3 <= (data_in_3_read_reg_1061 & ap_const_lv5_0);
    tmp_fu_441_p3 <= (p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_0 & ap_const_lv7_0);
    zext_ln46_10_fu_583_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_fu_576_p3),16));
    zext_ln46_11_fu_636_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln46_2_fu_630_p2),17));
    zext_ln46_18_fu_594_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_fu_587_p3),16));
    zext_ln46_19_fu_670_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln46_3_fu_664_p2),17));
    zext_ln46_2_fu_449_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_441_p3),16));
    zext_ln46_30_fu_615_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_4_fu_608_p3),16));
    zext_ln46_31_fu_702_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln46_4_fu_696_p2),17));
    zext_ln46_38_fu_626_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_5_fu_619_p3),16));
    zext_ln46_42_fu_648_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_6_fu_640_p3),16));
    zext_ln46_46_fu_660_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_7_fu_652_p3),16));
    zext_ln46_49_fu_681_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_8_fu_674_p3),16));
    zext_ln46_50_fu_692_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_9_fu_685_p3),16));
    zext_ln46_51_fu_361_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_10_fu_354_p3),16));
    zext_ln46_52_fu_372_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_11_fu_365_p3),16));
    zext_ln46_53_fu_509_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_12_fu_501_p3),16));
    zext_ln46_54_fu_521_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_13_fu_513_p3),16));
    zext_ln46_55_fu_542_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_14_fu_535_p3),16));
    zext_ln46_56_fu_553_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_15_fu_546_p3),16));
    zext_ln46_6_fu_461_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_453_p3),16));
    zext_ln46_7_fu_604_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln46_1_fu_598_p2),17));
    zext_ln92_10_fu_807_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln92_15_reg_1128),20));
    zext_ln92_11_fu_766_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_907_p3),19));
    zext_ln92_12_fu_769_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_925_p3),18));
    zext_ln92_13_fu_772_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_916_p3),18));
    zext_ln92_14_fu_781_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln92_20_fu_775_p2),19));
    zext_ln92_15_fu_810_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln92_21_reg_1133),20));
    zext_ln92_1_fu_711_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln92_1_fu_706_p2),18));
    zext_ln92_2_fu_720_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln92_3_fu_715_p2),18));
    zext_ln92_3_fu_791_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln92_4_reg_1118),19));
    zext_ln92_4_fu_735_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln92_6_fu_730_p2),18));
    zext_ln92_5_fu_744_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln92_8_fu_739_p2),18));
    zext_ln92_6_fu_794_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln92_9_reg_1123),19));
    zext_ln92_7_fu_803_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln92_10_fu_797_p2),20));
    zext_ln92_8_fu_754_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_871_p3),18));
    zext_ln92_9_fu_757_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_898_p3),18));
end behav;
