domain_path: /home/szymon/Desktop/CORA_Z7/HelloWorld/PLPS_HelloWorld_PS/AND_gate_platform/export/AND_gate_platform/sw/standalone_ps7_cortexa9_0
app_src_dir: /home/szymon/tools/Xilinx/2025.1/Vitis/data/embeddedsw/lib/sw_apps/hello_world
template: hello_world
lang: c
