// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="ImgSharpeningFilter_ImgSharpeningFilter,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z007s-clg400-1,HLS_INPUT_CLOCK=8.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.301000,HLS_SYN_LAT=2,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=153,HLS_SYN_LUT=228,HLS_VERSION=2025_1}" *)

module ImgSharpeningFilter (
        ap_clk,
        ap_rst_n,
        s_axi_CTRL_AWVALID,
        s_axi_CTRL_AWREADY,
        s_axi_CTRL_AWADDR,
        s_axi_CTRL_WVALID,
        s_axi_CTRL_WREADY,
        s_axi_CTRL_WDATA,
        s_axi_CTRL_WSTRB,
        s_axi_CTRL_ARVALID,
        s_axi_CTRL_ARREADY,
        s_axi_CTRL_ARADDR,
        s_axi_CTRL_RVALID,
        s_axi_CTRL_RREADY,
        s_axi_CTRL_RDATA,
        s_axi_CTRL_RRESP,
        s_axi_CTRL_BVALID,
        s_axi_CTRL_BREADY,
        s_axi_CTRL_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;
parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   s_axi_CTRL_AWVALID;
output   s_axi_CTRL_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_AWADDR;
input   s_axi_CTRL_WVALID;
output   s_axi_CTRL_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_CTRL_WSTRB;
input   s_axi_CTRL_ARVALID;
output   s_axi_CTRL_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_ARADDR;
output   s_axi_CTRL_RVALID;
input   s_axi_CTRL_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_RDATA;
output  [1:0] s_axi_CTRL_RRESP;
output   s_axi_CTRL_BVALID;
input   s_axi_CTRL_BREADY;
output  [1:0] s_axi_CTRL_BRESP;
output   interrupt;

(* shreg_extract = "no" *) reg    ap_rst_reg_2;
(* shreg_extract = "no" *) reg    ap_rst_reg_1;
(* shreg_extract = "no" *) reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
wire    ap_continue;
reg    ap_done_reg;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [7:0] data_in_0;
wire   [7:0] data_in_1;
wire   [7:0] data_in_2;
reg   [7:0] p_ZZ19ImgSharpeningFilter7ap_uintILi8EES0_S0_E13data_in_array_0_0;
reg   [7:0] p_ZZ19ImgSharpeningFilter7ap_uintILi8EES0_S0_E13data_in_array_1_1;
reg   [7:0] p_ZZ19ImgSharpeningFilter7ap_uintILi8EES0_S0_E13data_in_array_1_0;
reg   [7:0] p_ZZ19ImgSharpeningFilter7ap_uintILi8EES0_S0_E13data_in_array_2_0;
wire   [7:0] ap_return;
reg   [7:0] data_in_1_read_reg_244;
reg    ap_block_state1;
wire   [8:0] add_ln49_fu_98_p2;
reg   [8:0] add_ln49_reg_249;
reg   [2:0] tmp_2_reg_254;
wire    ap_CS_fsm_state2;
wire   [7:0] trunc_ln58_fu_216_p1;
reg   [7:0] trunc_ln58_reg_259;
wire    ap_CS_fsm_state3;
wire   [8:0] zext_ln38_1_fu_90_p1;
wire   [8:0] zext_ln38_3_fu_94_p1;
wire   [9:0] tmp_fu_139_p3;
wire   [10:0] zext_ln49_3_fu_147_p1;
wire   [10:0] zext_ln38_2_fu_131_p1;
wire   [10:0] add_ln49_2_fu_151_p2;
wire   [9:0] zext_ln49_1_fu_161_p1;
wire   [9:0] zext_ln38_fu_127_p1;
wire   [9:0] add_ln49_1_fu_164_p2;
wire   [11:0] zext_ln43_fu_157_p1;
wire   [11:0] zext_ln49_2_fu_170_p1;
wire   [11:0] AddRes_3_fu_174_p2;
wire   [11:0] zext_ln49_fu_135_p1;
wire   [11:0] AddRes_fu_180_p2;
wire   [0:0] tmp_1_fu_190_p3;
wire   [10:0] trunc_ln43_fu_186_p1;
wire   [10:0] AddRes_2_fu_198_p3;
wire   [0:0] icmp_ln55_fu_232_p2;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_rst_reg_2 = 1'b1;
#0 ap_rst_reg_1 = 1'b1;
#0 ap_rst_n_inv = 1'b1;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 p_ZZ19ImgSharpeningFilter7ap_uintILi8EES0_S0_E13data_in_array_0_0 = 8'd0;
#0 p_ZZ19ImgSharpeningFilter7ap_uintILi8EES0_S0_E13data_in_array_1_1 = 8'd0;
#0 p_ZZ19ImgSharpeningFilter7ap_uintILi8EES0_S0_E13data_in_array_1_0 = 8'd0;
#0 p_ZZ19ImgSharpeningFilter7ap_uintILi8EES0_S0_E13data_in_array_2_0 = 8'd0;
end

ImgSharpeningFilter_CTRL_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
CTRL_s_axi_U(
    .AWVALID(s_axi_CTRL_AWVALID),
    .AWREADY(s_axi_CTRL_AWREADY),
    .AWADDR(s_axi_CTRL_AWADDR),
    .WVALID(s_axi_CTRL_WVALID),
    .WREADY(s_axi_CTRL_WREADY),
    .WDATA(s_axi_CTRL_WDATA),
    .WSTRB(s_axi_CTRL_WSTRB),
    .ARVALID(s_axi_CTRL_ARVALID),
    .ARREADY(s_axi_CTRL_ARREADY),
    .ARADDR(s_axi_CTRL_ARADDR),
    .RVALID(s_axi_CTRL_RVALID),
    .RREADY(s_axi_CTRL_RREADY),
    .RDATA(s_axi_CTRL_RDATA),
    .RRESP(s_axi_CTRL_RRESP),
    .BVALID(s_axi_CTRL_BVALID),
    .BREADY(s_axi_CTRL_BREADY),
    .BRESP(s_axi_CTRL_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_continue(ap_continue),
    .ap_idle(ap_idle),
    .ap_return(ap_return),
    .data_in_0(data_in_0),
    .data_in_1(data_in_1),
    .data_in_2(data_in_2)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    ap_rst_n_inv <= ap_rst_reg_1;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_1 <= ap_rst_reg_2;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_2 <= ~ap_rst_n;
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        add_ln49_reg_249 <= add_ln49_fu_98_p2;
        data_in_1_read_reg_244 <= data_in_1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        p_ZZ19ImgSharpeningFilter7ap_uintILi8EES0_S0_E13data_in_array_0_0 <= data_in_0;
        p_ZZ19ImgSharpeningFilter7ap_uintILi8EES0_S0_E13data_in_array_2_0 <= data_in_2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        p_ZZ19ImgSharpeningFilter7ap_uintILi8EES0_S0_E13data_in_array_1_0 <= data_in_1_read_reg_244;
        p_ZZ19ImgSharpeningFilter7ap_uintILi8EES0_S0_E13data_in_array_1_1 <= p_ZZ19ImgSharpeningFilter7ap_uintILi8EES0_S0_E13data_in_array_1_0;
        tmp_2_reg_254 <= {{AddRes_2_fu_198_p3[10:8]}};
        trunc_ln58_reg_259 <= trunc_ln58_fu_216_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign AddRes_2_fu_198_p3 = ((tmp_1_fu_190_p3[0:0] == 1'b1) ? 11'd0 : trunc_ln43_fu_186_p1);

assign AddRes_3_fu_174_p2 = (zext_ln43_fu_157_p1 - zext_ln49_2_fu_170_p1);

assign AddRes_fu_180_p2 = (AddRes_3_fu_174_p2 - zext_ln49_fu_135_p1);

assign add_ln49_1_fu_164_p2 = (zext_ln49_1_fu_161_p1 + zext_ln38_fu_127_p1);

assign add_ln49_2_fu_151_p2 = (zext_ln49_3_fu_147_p1 + zext_ln38_2_fu_131_p1);

assign add_ln49_fu_98_p2 = (zext_ln38_1_fu_90_p1 + zext_ln38_3_fu_94_p1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign ap_return = ((icmp_ln55_fu_232_p2[0:0] == 1'b1) ? 8'd255 : trunc_ln58_reg_259);

assign icmp_ln55_fu_232_p2 = ((tmp_2_reg_254 != 3'd0) ? 1'b1 : 1'b0);

assign tmp_1_fu_190_p3 = AddRes_fu_180_p2[32'd11];

assign tmp_fu_139_p3 = {{p_ZZ19ImgSharpeningFilter7ap_uintILi8EES0_S0_E13data_in_array_1_0}, {2'd0}};

assign trunc_ln43_fu_186_p1 = AddRes_fu_180_p2[10:0];

assign trunc_ln58_fu_216_p1 = AddRes_2_fu_198_p3[7:0];

assign zext_ln38_1_fu_90_p1 = data_in_1;

assign zext_ln38_2_fu_131_p1 = p_ZZ19ImgSharpeningFilter7ap_uintILi8EES0_S0_E13data_in_array_1_0;

assign zext_ln38_3_fu_94_p1 = p_ZZ19ImgSharpeningFilter7ap_uintILi8EES0_S0_E13data_in_array_1_1;

assign zext_ln38_fu_127_p1 = p_ZZ19ImgSharpeningFilter7ap_uintILi8EES0_S0_E13data_in_array_0_0;

assign zext_ln43_fu_157_p1 = add_ln49_2_fu_151_p2;

assign zext_ln49_1_fu_161_p1 = add_ln49_reg_249;

assign zext_ln49_2_fu_170_p1 = add_ln49_1_fu_164_p2;

assign zext_ln49_3_fu_147_p1 = tmp_fu_139_p3;

assign zext_ln49_fu_135_p1 = p_ZZ19ImgSharpeningFilter7ap_uintILi8EES0_S0_E13data_in_array_2_0;

endmodule //ImgSharpeningFilter
