// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="GaussianFilter_GaussianFilter,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z007s-clg400-1,HLS_INPUT_CLOCK=8.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.450000,HLS_SYN_LAT=5,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=469,HLS_SYN_LUT=959,HLS_VERSION=2025_1}" *)

module GaussianFilter (
        ap_clk,
        ap_rst_n,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

(* shreg_extract = "no" *) reg    ap_rst_reg_2;
(* shreg_extract = "no" *) reg    ap_rst_reg_1;
(* shreg_extract = "no" *) reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
wire    ap_continue;
reg    ap_done_reg;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [7:0] data_in_0;
wire   [7:0] data_in_1;
wire   [7:0] data_in_2;
wire   [7:0] data_in_3;
wire   [7:0] data_in_4;
reg   [7:0] p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_3;
reg   [7:0] p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_2;
reg   [7:0] p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_1;
reg   [7:0] p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_0;
reg   [7:0] p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_3;
reg   [7:0] p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_2;
reg   [7:0] p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_1;
reg   [7:0] p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_0;
reg   [7:0] p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_3;
reg   [7:0] p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_2;
reg   [7:0] p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_1;
reg   [7:0] p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_0;
reg   [7:0] p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_3;
reg   [7:0] p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_2;
reg   [7:0] p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_1;
reg   [7:0] p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_0;
reg   [7:0] p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_3;
reg   [7:0] p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_2;
reg   [7:0] p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_1;
reg   [7:0] p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_0;
wire   [31:0] ap_return;
reg   [7:0] p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_3_load_reg_934;
reg    ap_block_state1;
reg   [7:0] p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_1_load_reg_939;
reg   [7:0] p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_1_load_reg_944;
reg   [7:0] p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_2_load_reg_965;
wire    ap_CS_fsm_state2;
reg   [7:0] p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_2_load_reg_971;
reg   [7:0] p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_3_load_reg_977;
reg   [7:0] p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_2_load_reg_983;
reg   [7:0] data_in_4_read_reg_1034;
wire    ap_CS_fsm_state3;
reg   [7:0] data_in_0_read_reg_1040;
reg   [7:0] data_in_3_read_reg_1061;
wire    ap_CS_fsm_state4;
reg   [7:0] data_in_1_read_reg_1067;
wire   [16:0] grp_fu_837_p3;
wire   [16:0] grp_fu_829_p3;
wire   [16:0] grp_fu_845_p3;
wire   [17:0] add_ln92_4_fu_724_p2;
reg   [17:0] add_ln92_4_reg_1118;
wire    ap_CS_fsm_state5;
wire   [17:0] add_ln92_9_fu_748_p2;
reg   [17:0] add_ln92_9_reg_1123;
wire   [17:0] add_ln92_15_fu_760_p2;
reg   [17:0] add_ln92_15_reg_1128;
wire   [18:0] add_ln92_21_fu_785_p2;
reg   [18:0] add_ln92_21_reg_1133;
wire   [7:0] mul_ln46_10_fu_331_p0;
wire   [8:0] mul_ln46_10_fu_331_p1;
wire   [15:0] mul_ln46_10_fu_331_p2;
wire   [7:0] mul_ln46_12_fu_344_p0;
wire   [8:0] mul_ln46_12_fu_344_p1;
wire   [15:0] mul_ln46_12_fu_344_p2;
wire   [14:0] tmp_10_fu_354_p3;
wire   [12:0] tmp_11_fu_365_p3;
wire   [15:0] zext_ln46_51_fu_361_p1;
wire   [15:0] zext_ln46_52_fu_372_p1;
wire   [15:0] add_ln46_5_fu_376_p2;
wire   [7:0] mul_ln46_fu_431_p0;
wire   [8:0] mul_ln46_fu_431_p1;
wire   [15:0] mul_ln46_fu_431_p2;
wire   [14:0] tmp_fu_441_p3;
wire   [12:0] tmp_1_fu_453_p3;
wire   [15:0] zext_ln46_2_fu_449_p1;
wire   [15:0] zext_ln46_6_fu_461_p1;
wire   [15:0] add_ln46_fu_465_p2;
wire   [7:0] mul_ln46_5_fu_478_p0;
wire   [8:0] mul_ln46_5_fu_478_p1;
wire   [15:0] mul_ln46_5_fu_478_p2;
wire   [7:0] mul_ln46_14_fu_491_p0;
wire   [8:0] mul_ln46_14_fu_491_p1;
wire   [15:0] mul_ln46_14_fu_491_p2;
wire   [14:0] tmp_12_fu_501_p3;
wire   [12:0] tmp_13_fu_513_p3;
wire   [15:0] zext_ln46_53_fu_509_p1;
wire   [15:0] zext_ln46_54_fu_521_p1;
wire   [15:0] add_ln46_6_fu_525_p2;
wire   [14:0] tmp_14_fu_535_p3;
wire   [12:0] tmp_15_fu_546_p3;
wire   [15:0] zext_ln46_55_fu_542_p1;
wire   [15:0] zext_ln46_56_fu_553_p1;
wire   [15:0] add_ln46_7_fu_557_p2;
wire   [14:0] tmp_2_fu_576_p3;
wire   [12:0] tmp_3_fu_587_p3;
wire   [15:0] zext_ln46_10_fu_583_p1;
wire   [15:0] zext_ln46_18_fu_594_p1;
wire   [15:0] add_ln46_1_fu_598_p2;
wire   [14:0] tmp_4_fu_608_p3;
wire   [12:0] tmp_5_fu_619_p3;
wire   [15:0] zext_ln46_30_fu_615_p1;
wire   [15:0] zext_ln46_38_fu_626_p1;
wire   [15:0] add_ln46_2_fu_630_p2;
wire   [14:0] tmp_6_fu_640_p3;
wire   [12:0] tmp_7_fu_652_p3;
wire   [15:0] zext_ln46_42_fu_648_p1;
wire   [15:0] zext_ln46_46_fu_660_p1;
wire   [15:0] add_ln46_3_fu_664_p2;
wire   [14:0] tmp_8_fu_674_p3;
wire   [12:0] tmp_9_fu_685_p3;
wire   [15:0] zext_ln46_49_fu_681_p1;
wire   [15:0] zext_ln46_50_fu_692_p1;
wire   [15:0] add_ln46_4_fu_696_p2;
wire   [16:0] grp_fu_889_p3;
wire   [16:0] zext_ln46_11_fu_636_p1;
(* use_dsp48 = "no" *) wire   [16:0] add_ln92_1_fu_706_p2;
wire   [16:0] grp_fu_862_p3;
wire   [16:0] zext_ln46_31_fu_702_p1;
(* use_dsp48 = "no" *) wire   [16:0] add_ln92_3_fu_715_p2;
wire   [17:0] zext_ln92_2_fu_720_p1;
wire   [17:0] zext_ln92_1_fu_711_p1;
wire   [16:0] grp_fu_853_p3;
wire   [16:0] zext_ln46_7_fu_604_p1;
(* use_dsp48 = "no" *) wire   [16:0] add_ln92_6_fu_730_p2;
wire   [16:0] grp_fu_880_p3;
wire   [16:0] zext_ln46_19_fu_670_p1;
(* use_dsp48 = "no" *) wire   [16:0] add_ln92_8_fu_739_p2;
wire   [17:0] zext_ln92_5_fu_744_p1;
wire   [17:0] zext_ln92_4_fu_735_p1;
wire   [16:0] grp_fu_871_p3;
wire   [16:0] grp_fu_898_p3;
wire   [17:0] zext_ln92_9_fu_757_p1;
wire   [17:0] zext_ln92_8_fu_754_p1;
wire   [16:0] grp_fu_907_p3;
wire   [16:0] grp_fu_925_p3;
wire   [16:0] grp_fu_916_p3;
wire   [17:0] zext_ln92_13_fu_772_p1;
wire   [17:0] zext_ln92_12_fu_769_p1;
wire   [17:0] add_ln92_20_fu_775_p2;
wire   [18:0] zext_ln92_14_fu_781_p1;
wire   [18:0] zext_ln92_11_fu_766_p1;
wire    ap_CS_fsm_state6;
wire   [18:0] zext_ln92_6_fu_794_p1;
wire   [18:0] zext_ln92_3_fu_791_p1;
wire   [18:0] add_ln92_10_fu_797_p2;
wire   [19:0] zext_ln92_15_fu_810_p1;
wire   [19:0] zext_ln92_10_fu_807_p1;
wire   [19:0] add_ln92_22_fu_813_p2;
wire   [19:0] zext_ln92_7_fu_803_p1;
wire   [19:0] add_ln92_23_fu_819_p2;
wire   [7:0] grp_fu_829_p0;
wire   [7:0] grp_fu_829_p1;
wire   [15:0] grp_fu_829_p2;
wire   [7:0] grp_fu_837_p0;
wire   [7:0] grp_fu_837_p1;
wire   [15:0] grp_fu_837_p2;
wire   [7:0] grp_fu_845_p0;
wire   [7:0] grp_fu_845_p1;
wire   [15:0] grp_fu_845_p2;
wire   [7:0] grp_fu_853_p0;
wire   [7:0] grp_fu_853_p1;
wire   [15:0] grp_fu_853_p2;
wire   [7:0] grp_fu_862_p0;
wire   [7:0] grp_fu_862_p1;
wire   [15:0] grp_fu_862_p2;
wire   [7:0] grp_fu_871_p0;
wire   [7:0] grp_fu_871_p1;
wire   [7:0] grp_fu_880_p0;
wire   [7:0] grp_fu_880_p1;
wire   [15:0] grp_fu_880_p2;
wire   [7:0] grp_fu_889_p0;
wire   [7:0] grp_fu_889_p1;
wire   [15:0] grp_fu_889_p2;
wire   [7:0] grp_fu_898_p0;
wire   [7:0] grp_fu_898_p1;
wire   [7:0] grp_fu_907_p0;
wire   [7:0] grp_fu_907_p1;
wire   [7:0] grp_fu_916_p0;
wire   [7:0] grp_fu_916_p1;
wire   [15:0] grp_fu_916_p2;
wire   [7:0] grp_fu_925_p0;
wire   [7:0] grp_fu_925_p1;
wire   [15:0] grp_fu_925_p2;
reg    grp_fu_829_ce;
reg    grp_fu_837_ce;
reg    grp_fu_845_ce;
reg   [5:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire   [15:0] grp_fu_829_p00;
wire   [16:0] grp_fu_829_p20;
wire   [15:0] grp_fu_837_p00;
wire   [16:0] grp_fu_837_p20;
wire   [15:0] grp_fu_845_p00;
wire   [16:0] grp_fu_845_p20;
wire   [15:0] grp_fu_853_p00;
wire   [16:0] grp_fu_853_p20;
wire   [15:0] grp_fu_862_p00;
wire   [16:0] grp_fu_862_p20;
wire   [15:0] grp_fu_871_p00;
wire   [15:0] grp_fu_880_p00;
wire   [16:0] grp_fu_880_p20;
wire   [15:0] grp_fu_889_p00;
wire   [16:0] grp_fu_889_p20;
wire   [15:0] grp_fu_898_p00;
wire   [15:0] grp_fu_907_p00;
wire   [15:0] grp_fu_916_p00;
wire   [16:0] grp_fu_916_p20;
wire   [15:0] grp_fu_925_p00;
wire   [16:0] grp_fu_925_p20;
wire   [15:0] mul_ln46_10_fu_331_p00;
wire   [15:0] mul_ln46_12_fu_344_p00;
wire   [15:0] mul_ln46_14_fu_491_p00;
wire   [15:0] mul_ln46_5_fu_478_p00;
wire   [15:0] mul_ln46_fu_431_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_rst_reg_2 = 1'b1;
#0 ap_rst_reg_1 = 1'b1;
#0 ap_rst_n_inv = 1'b1;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 6'd1;
#0 p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_3 = 8'd0;
#0 p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_2 = 8'd0;
#0 p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_1 = 8'd0;
#0 p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_0 = 8'd0;
#0 p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_3 = 8'd0;
#0 p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_2 = 8'd0;
#0 p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_1 = 8'd0;
#0 p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_0 = 8'd0;
#0 p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_3 = 8'd0;
#0 p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_2 = 8'd0;
#0 p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_1 = 8'd0;
#0 p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_0 = 8'd0;
#0 p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_3 = 8'd0;
#0 p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_2 = 8'd0;
#0 p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_1 = 8'd0;
#0 p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_0 = 8'd0;
#0 p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_3 = 8'd0;
#0 p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_2 = 8'd0;
#0 p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_1 = 8'd0;
#0 p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_0 = 8'd0;
end

GaussianFilter_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_continue(ap_continue),
    .ap_idle(ap_idle),
    .ap_return(ap_return),
    .data_in_0(data_in_0),
    .data_in_1(data_in_1),
    .data_in_2(data_in_2),
    .data_in_3(data_in_3),
    .data_in_4(data_in_4)
);

GaussianFilter_mul_8ns_9ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 16 ))
mul_8ns_9ns_16_1_1_U1(
    .din0(mul_ln46_10_fu_331_p0),
    .din1(mul_ln46_10_fu_331_p1),
    .dout(mul_ln46_10_fu_331_p2)
);

GaussianFilter_mul_8ns_9ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 16 ))
mul_8ns_9ns_16_1_1_U2(
    .din0(mul_ln46_12_fu_344_p0),
    .din1(mul_ln46_12_fu_344_p1),
    .dout(mul_ln46_12_fu_344_p2)
);

GaussianFilter_mul_8ns_9ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 16 ))
mul_8ns_9ns_16_1_1_U3(
    .din0(mul_ln46_fu_431_p0),
    .din1(mul_ln46_fu_431_p1),
    .dout(mul_ln46_fu_431_p2)
);

GaussianFilter_mul_8ns_9ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 16 ))
mul_8ns_9ns_16_1_1_U4(
    .din0(mul_ln46_5_fu_478_p0),
    .din1(mul_ln46_5_fu_478_p1),
    .dout(mul_ln46_5_fu_478_p2)
);

GaussianFilter_mul_8ns_9ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 16 ))
mul_8ns_9ns_16_1_1_U5(
    .din0(mul_ln46_14_fu_491_p0),
    .din1(mul_ln46_14_fu_491_p1),
    .dout(mul_ln46_14_fu_491_p2)
);

GaussianFilter_mac_muladd_8ns_8ns_16ns_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_8ns_16ns_17_4_1_U6(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_829_p0),
    .din1(grp_fu_829_p1),
    .din2(grp_fu_829_p2),
    .ce(grp_fu_829_ce),
    .dout(grp_fu_829_p3)
);

GaussianFilter_mac_muladd_8ns_8ns_16ns_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_8ns_16ns_17_4_1_U7(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_837_p0),
    .din1(grp_fu_837_p1),
    .din2(grp_fu_837_p2),
    .ce(grp_fu_837_ce),
    .dout(grp_fu_837_p3)
);

GaussianFilter_mac_muladd_8ns_8ns_16ns_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_8ns_16ns_17_4_1_U8(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_845_p0),
    .din1(grp_fu_845_p1),
    .din2(grp_fu_845_p2),
    .ce(grp_fu_845_ce),
    .dout(grp_fu_845_p3)
);

GaussianFilter_mac_muladd_8ns_8ns_16ns_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_8ns_16ns_17_4_1_U9(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_853_p0),
    .din1(grp_fu_853_p1),
    .din2(grp_fu_853_p2),
    .ce(1'b1),
    .dout(grp_fu_853_p3)
);

GaussianFilter_mac_muladd_8ns_8ns_16ns_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_8ns_16ns_17_4_1_U10(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_862_p0),
    .din1(grp_fu_862_p1),
    .din2(grp_fu_862_p2),
    .ce(1'b1),
    .dout(grp_fu_862_p3)
);

GaussianFilter_mac_muladd_8ns_8ns_17ns_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_8ns_17ns_17_4_1_U11(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_871_p0),
    .din1(grp_fu_871_p1),
    .din2(grp_fu_837_p3),
    .ce(1'b1),
    .dout(grp_fu_871_p3)
);

GaussianFilter_mac_muladd_8ns_8ns_16ns_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_8ns_16ns_17_4_1_U12(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_880_p0),
    .din1(grp_fu_880_p1),
    .din2(grp_fu_880_p2),
    .ce(1'b1),
    .dout(grp_fu_880_p3)
);

GaussianFilter_mac_muladd_8ns_8ns_16ns_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_8ns_16ns_17_4_1_U13(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_889_p0),
    .din1(grp_fu_889_p1),
    .din2(grp_fu_889_p2),
    .ce(1'b1),
    .dout(grp_fu_889_p3)
);

GaussianFilter_mac_muladd_8ns_8ns_17ns_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_8ns_17ns_17_4_1_U14(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_898_p0),
    .din1(grp_fu_898_p1),
    .din2(grp_fu_829_p3),
    .ce(1'b1),
    .dout(grp_fu_898_p3)
);

GaussianFilter_mac_muladd_8ns_8ns_17ns_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_8ns_17ns_17_4_1_U15(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_907_p0),
    .din1(grp_fu_907_p1),
    .din2(grp_fu_845_p3),
    .ce(1'b1),
    .dout(grp_fu_907_p3)
);

GaussianFilter_mac_muladd_8ns_8ns_16ns_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_8ns_16ns_17_4_1_U16(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_916_p0),
    .din1(grp_fu_916_p1),
    .din2(grp_fu_916_p2),
    .ce(1'b1),
    .dout(grp_fu_916_p3)
);

GaussianFilter_mac_muladd_8ns_8ns_16ns_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_8ns_16ns_17_4_1_U17(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_925_p0),
    .din1(grp_fu_925_p1),
    .din2(grp_fu_925_p2),
    .ce(1'b1),
    .dout(grp_fu_925_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state6)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    ap_rst_n_inv <= ap_rst_reg_1;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_1 <= ap_rst_reg_2;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_2 <= ~ap_rst_n;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        add_ln92_15_reg_1128 <= add_ln92_15_fu_760_p2;
        add_ln92_21_reg_1133 <= add_ln92_21_fu_785_p2;
        add_ln92_4_reg_1118 <= add_ln92_4_fu_724_p2;
        add_ln92_9_reg_1123 <= add_ln92_9_fu_748_p2;
        p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_3 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_2_load_reg_971;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        data_in_0_read_reg_1040 <= data_in_0;
        data_in_4_read_reg_1034 <= data_in_4;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        data_in_1_read_reg_1067 <= data_in_1;
        data_in_3_read_reg_1061 <= data_in_3;
        p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_0 <= data_in_0_read_reg_1040;
        p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_1 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_0;
        p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_0 <= data_in_1;
        p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_0 <= data_in_3;
        p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_0 <= data_in_4_read_reg_1034;
        p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_1 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_2 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_1;
        p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_2_load_reg_965 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_2;
        p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_3 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_2;
        p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_1 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_0;
        p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_2 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_1;
        p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_2_load_reg_971 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_2;
        p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_0 <= data_in_2;
        p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_2 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_1_load_reg_944;
        p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_3 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_2;
        p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_3_load_reg_977 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_3;
        p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_2 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_1;
        p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_2_load_reg_983 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_2;
        p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_3 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_1 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_0;
        p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_1_load_reg_939 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_1;
        p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_2 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_1;
        p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_3 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_2;
        p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_3_load_reg_934 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_3;
        p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_1 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_0;
        p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_1_load_reg_944 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | ((1'b1 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1)))) begin
        grp_fu_829_ce = 1'b0;
    end else begin
        grp_fu_829_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | ((1'b1 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1)))) begin
        grp_fu_837_ce = 1'b0;
    end else begin
        grp_fu_837_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | ((1'b1 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1)))) begin
        grp_fu_845_ce = 1'b0;
    end else begin
        grp_fu_845_ce = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln46_1_fu_598_p2 = (zext_ln46_10_fu_583_p1 + zext_ln46_18_fu_594_p1);

assign add_ln46_2_fu_630_p2 = (zext_ln46_30_fu_615_p1 + zext_ln46_38_fu_626_p1);

assign add_ln46_3_fu_664_p2 = (zext_ln46_42_fu_648_p1 + zext_ln46_46_fu_660_p1);

assign add_ln46_4_fu_696_p2 = (zext_ln46_49_fu_681_p1 + zext_ln46_50_fu_692_p1);

assign add_ln46_5_fu_376_p2 = (zext_ln46_51_fu_361_p1 + zext_ln46_52_fu_372_p1);

assign add_ln46_6_fu_525_p2 = (zext_ln46_53_fu_509_p1 + zext_ln46_54_fu_521_p1);

assign add_ln46_7_fu_557_p2 = (zext_ln46_55_fu_542_p1 + zext_ln46_56_fu_553_p1);

assign add_ln46_fu_465_p2 = (zext_ln46_2_fu_449_p1 + zext_ln46_6_fu_461_p1);

assign add_ln92_10_fu_797_p2 = (zext_ln92_6_fu_794_p1 + zext_ln92_3_fu_791_p1);

assign add_ln92_15_fu_760_p2 = (zext_ln92_9_fu_757_p1 + zext_ln92_8_fu_754_p1);

assign add_ln92_1_fu_706_p2 = (grp_fu_889_p3 + zext_ln46_11_fu_636_p1);

assign add_ln92_20_fu_775_p2 = (zext_ln92_13_fu_772_p1 + zext_ln92_12_fu_769_p1);

assign add_ln92_21_fu_785_p2 = (zext_ln92_14_fu_781_p1 + zext_ln92_11_fu_766_p1);

assign add_ln92_22_fu_813_p2 = (zext_ln92_15_fu_810_p1 + zext_ln92_10_fu_807_p1);

assign add_ln92_23_fu_819_p2 = (add_ln92_22_fu_813_p2 + zext_ln92_7_fu_803_p1);

assign add_ln92_3_fu_715_p2 = (grp_fu_862_p3 + zext_ln46_31_fu_702_p1);

assign add_ln92_4_fu_724_p2 = (zext_ln92_2_fu_720_p1 + zext_ln92_1_fu_711_p1);

assign add_ln92_6_fu_730_p2 = (grp_fu_853_p3 + zext_ln46_7_fu_604_p1);

assign add_ln92_8_fu_739_p2 = (grp_fu_880_p3 + zext_ln46_19_fu_670_p1);

assign add_ln92_9_fu_748_p2 = (zext_ln92_5_fu_744_p1 + zext_ln92_4_fu_735_p1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign ap_return = add_ln92_23_fu_819_p2;

assign grp_fu_829_p0 = grp_fu_829_p00;

assign grp_fu_829_p00 = p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_0;

assign grp_fu_829_p1 = 16'd174;

assign grp_fu_829_p2 = grp_fu_829_p20;

assign grp_fu_829_p20 = add_ln46_5_fu_376_p2;

assign grp_fu_837_p0 = grp_fu_837_p00;

assign grp_fu_837_p00 = p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_2;

assign grp_fu_837_p1 = 16'd174;

assign grp_fu_837_p2 = grp_fu_837_p20;

assign grp_fu_837_p20 = mul_ln46_10_fu_331_p2;

assign grp_fu_845_p0 = grp_fu_845_p00;

assign grp_fu_845_p00 = p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_0;

assign grp_fu_845_p1 = 16'd170;

assign grp_fu_845_p2 = grp_fu_845_p20;

assign grp_fu_845_p20 = mul_ln46_12_fu_344_p2;

assign grp_fu_853_p0 = grp_fu_853_p00;

assign grp_fu_853_p00 = p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_1;

assign grp_fu_853_p1 = 16'd164;

assign grp_fu_853_p2 = grp_fu_853_p20;

assign grp_fu_853_p20 = add_ln46_fu_465_p2;

assign grp_fu_862_p0 = grp_fu_862_p00;

assign grp_fu_862_p00 = p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_3;

assign grp_fu_862_p1 = 16'd151;

assign grp_fu_862_p2 = grp_fu_862_p20;

assign grp_fu_862_p20 = mul_ln46_14_fu_491_p2;

assign grp_fu_871_p0 = grp_fu_871_p00;

assign grp_fu_871_p00 = p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_0;

assign grp_fu_871_p1 = 16'd170;

assign grp_fu_880_p0 = grp_fu_880_p00;

assign grp_fu_880_p00 = p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_1;

assign grp_fu_880_p1 = 16'd174;

assign grp_fu_880_p2 = grp_fu_880_p20;

assign grp_fu_880_p20 = mul_ln46_5_fu_478_p2;

assign grp_fu_889_p0 = grp_fu_889_p00;

assign grp_fu_889_p00 = data_in_2;

assign grp_fu_889_p1 = 16'd164;

assign grp_fu_889_p2 = grp_fu_889_p20;

assign grp_fu_889_p20 = mul_ln46_fu_431_p2;

assign grp_fu_898_p0 = grp_fu_898_p00;

assign grp_fu_898_p00 = p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_1_load_reg_939;

assign grp_fu_898_p1 = 16'd177;

assign grp_fu_907_p0 = grp_fu_907_p00;

assign grp_fu_907_p00 = p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_2;

assign grp_fu_907_p1 = 16'd170;

assign grp_fu_916_p0 = grp_fu_916_p00;

assign grp_fu_916_p00 = p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_1;

assign grp_fu_916_p1 = 16'd164;

assign grp_fu_916_p2 = grp_fu_916_p20;

assign grp_fu_916_p20 = add_ln46_6_fu_525_p2;

assign grp_fu_925_p0 = grp_fu_925_p00;

assign grp_fu_925_p00 = p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_3;

assign grp_fu_925_p1 = 16'd151;

assign grp_fu_925_p2 = grp_fu_925_p20;

assign grp_fu_925_p20 = add_ln46_7_fu_557_p2;

assign mul_ln46_10_fu_331_p0 = mul_ln46_10_fu_331_p00;

assign mul_ln46_10_fu_331_p00 = p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_3_load_reg_934;

assign mul_ln46_10_fu_331_p1 = 16'd164;

assign mul_ln46_12_fu_344_p0 = mul_ln46_12_fu_344_p00;

assign mul_ln46_12_fu_344_p00 = p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_1_load_reg_944;

assign mul_ln46_12_fu_344_p1 = 16'd174;

assign mul_ln46_14_fu_491_p0 = mul_ln46_14_fu_491_p00;

assign mul_ln46_14_fu_491_p00 = data_in_4_read_reg_1034;

assign mul_ln46_14_fu_491_p1 = 16'd151;

assign mul_ln46_5_fu_478_p0 = mul_ln46_5_fu_478_p00;

assign mul_ln46_5_fu_478_p00 = p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_2_load_reg_971;

assign mul_ln46_5_fu_478_p1 = 16'd170;

assign mul_ln46_fu_431_p0 = mul_ln46_fu_431_p00;

assign mul_ln46_fu_431_p00 = data_in_0_read_reg_1040;

assign mul_ln46_fu_431_p1 = 16'd151;

assign tmp_10_fu_354_p3 = {{p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_3_load_reg_977}, {7'd0}};

assign tmp_11_fu_365_p3 = {{p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_3_load_reg_977}, {5'd0}};

assign tmp_12_fu_501_p3 = {{p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_0}, {7'd0}};

assign tmp_13_fu_513_p3 = {{p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_0}, {5'd0}};

assign tmp_14_fu_535_p3 = {{p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_2_load_reg_983}, {7'd0}};

assign tmp_15_fu_546_p3 = {{p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_2_load_reg_983}, {5'd0}};

assign tmp_1_fu_453_p3 = {{p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_0}, {5'd0}};

assign tmp_2_fu_576_p3 = {{p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_2_load_reg_965}, {7'd0}};

assign tmp_3_fu_587_p3 = {{p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_2_load_reg_965}, {5'd0}};

assign tmp_4_fu_608_p3 = {{data_in_1_read_reg_1067}, {7'd0}};

assign tmp_5_fu_619_p3 = {{data_in_1_read_reg_1067}, {5'd0}};

assign tmp_6_fu_640_p3 = {{p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_3}, {7'd0}};

assign tmp_7_fu_652_p3 = {{p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_3}, {5'd0}};

assign tmp_8_fu_674_p3 = {{data_in_3_read_reg_1061}, {7'd0}};

assign tmp_9_fu_685_p3 = {{data_in_3_read_reg_1061}, {5'd0}};

assign tmp_fu_441_p3 = {{p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_0}, {7'd0}};

assign zext_ln46_10_fu_583_p1 = tmp_2_fu_576_p3;

assign zext_ln46_11_fu_636_p1 = add_ln46_2_fu_630_p2;

assign zext_ln46_18_fu_594_p1 = tmp_3_fu_587_p3;

assign zext_ln46_19_fu_670_p1 = add_ln46_3_fu_664_p2;

assign zext_ln46_2_fu_449_p1 = tmp_fu_441_p3;

assign zext_ln46_30_fu_615_p1 = tmp_4_fu_608_p3;

assign zext_ln46_31_fu_702_p1 = add_ln46_4_fu_696_p2;

assign zext_ln46_38_fu_626_p1 = tmp_5_fu_619_p3;

assign zext_ln46_42_fu_648_p1 = tmp_6_fu_640_p3;

assign zext_ln46_46_fu_660_p1 = tmp_7_fu_652_p3;

assign zext_ln46_49_fu_681_p1 = tmp_8_fu_674_p3;

assign zext_ln46_50_fu_692_p1 = tmp_9_fu_685_p3;

assign zext_ln46_51_fu_361_p1 = tmp_10_fu_354_p3;

assign zext_ln46_52_fu_372_p1 = tmp_11_fu_365_p3;

assign zext_ln46_53_fu_509_p1 = tmp_12_fu_501_p3;

assign zext_ln46_54_fu_521_p1 = tmp_13_fu_513_p3;

assign zext_ln46_55_fu_542_p1 = tmp_14_fu_535_p3;

assign zext_ln46_56_fu_553_p1 = tmp_15_fu_546_p3;

assign zext_ln46_6_fu_461_p1 = tmp_1_fu_453_p3;

assign zext_ln46_7_fu_604_p1 = add_ln46_1_fu_598_p2;

assign zext_ln92_10_fu_807_p1 = add_ln92_15_reg_1128;

assign zext_ln92_11_fu_766_p1 = grp_fu_907_p3;

assign zext_ln92_12_fu_769_p1 = grp_fu_925_p3;

assign zext_ln92_13_fu_772_p1 = grp_fu_916_p3;

assign zext_ln92_14_fu_781_p1 = add_ln92_20_fu_775_p2;

assign zext_ln92_15_fu_810_p1 = add_ln92_21_reg_1133;

assign zext_ln92_1_fu_711_p1 = add_ln92_1_fu_706_p2;

assign zext_ln92_2_fu_720_p1 = add_ln92_3_fu_715_p2;

assign zext_ln92_3_fu_791_p1 = add_ln92_4_reg_1118;

assign zext_ln92_4_fu_735_p1 = add_ln92_6_fu_730_p2;

assign zext_ln92_5_fu_744_p1 = add_ln92_8_fu_739_p2;

assign zext_ln92_6_fu_794_p1 = add_ln92_9_reg_1123;

assign zext_ln92_7_fu_803_p1 = add_ln92_10_fu_797_p2;

assign zext_ln92_8_fu_754_p1 = grp_fu_871_p3;

assign zext_ln92_9_fu_757_p1 = grp_fu_898_p3;

endmodule //GaussianFilter
