domain_path: /home/szymon/Desktop/CORA_Z7/projekt/PLPS_HelloWorld_PS/gauss_1_platform/zynq_fsbl/zynq_fsbl_bsp
app_src_dir: /home/szymon/tools/Xilinx/2025.1/Vitis/data/embeddedsw/lib/sw_apps/zynq_fsbl
template: zynq_fsbl
lang: c
