-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity GaussianFilter is
generic (
    C_S_AXI_CTRL_ADDR_WIDTH : INTEGER := 6;
    C_S_AXI_CTRL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    s_axi_CTRL_AWVALID : IN STD_LOGIC;
    s_axi_CTRL_AWREADY : OUT STD_LOGIC;
    s_axi_CTRL_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_WVALID : IN STD_LOGIC;
    s_axi_CTRL_WREADY : OUT STD_LOGIC;
    s_axi_CTRL_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH/8-1 downto 0);
    s_axi_CTRL_ARVALID : IN STD_LOGIC;
    s_axi_CTRL_ARREADY : OUT STD_LOGIC;
    s_axi_CTRL_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_RVALID : OUT STD_LOGIC;
    s_axi_CTRL_RREADY : IN STD_LOGIC;
    s_axi_CTRL_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_CTRL_BVALID : OUT STD_LOGIC;
    s_axi_CTRL_BREADY : IN STD_LOGIC;
    s_axi_CTRL_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of GaussianFilter is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "GaussianFilter_GaussianFilter,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z007s-clg400-1,HLS_INPUT_CLOCK=8.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.450000,HLS_SYN_LAT=5,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=469,HLS_SYN_LUT=959,HLS_VERSION=2025_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_lv16_A4 : STD_LOGIC_VECTOR (15 downto 0) := "0000000010100100";
    constant ap_const_lv16_AE : STD_LOGIC_VECTOR (15 downto 0) := "0000000010101110";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv16_97 : STD_LOGIC_VECTOR (15 downto 0) := "0000000010010111";
    constant ap_const_lv16_AA : STD_LOGIC_VECTOR (15 downto 0) := "0000000010101010";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv16_B1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000010110001";

attribute shreg_extract : string;
    signal ap_rst_reg_2 : STD_LOGIC := '1';
attribute shreg_extract of ap_rst_reg_2 : signal is "no";
    signal ap_rst_reg_1 : STD_LOGIC := '1';
attribute shreg_extract of ap_rst_reg_1 : signal is "no";
    signal ap_rst_n_inv : STD_LOGIC := '1';
attribute shreg_extract of ap_rst_n_inv : signal is "no";
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_continue : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal data_in_0 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_in_1 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_in_2 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_in_3 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_in_4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_3 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_3 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_3 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_3 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_3 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_return : STD_LOGIC_VECTOR (31 downto 0);
    signal p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_3_load_reg_932 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_1_load_reg_937 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_1_load_reg_942 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_2_load_reg_963 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_2_load_reg_969 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_3_load_reg_975 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_2_load_reg_981 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_in_4_read_reg_1032 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal data_in_0_read_reg_1038 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_in_3_read_reg_1059 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal data_in_1_read_reg_1065 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_835_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_827_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_843_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln93_4_fu_722_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln93_4_reg_1116 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal add_ln93_9_fu_746_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln93_9_reg_1121 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln93_15_fu_758_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln93_15_reg_1126 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln93_21_fu_783_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal add_ln93_21_reg_1131 : STD_LOGIC_VECTOR (18 downto 0);
    signal mul_ln47_10_fu_329_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln47_10_fu_329_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln47_10_fu_329_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln47_12_fu_342_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln47_12_fu_342_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln47_12_fu_342_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_10_fu_352_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_11_fu_363_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln47_51_fu_359_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln47_52_fu_370_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln47_5_fu_374_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln47_fu_429_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln47_fu_429_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln47_fu_429_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_fu_439_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_1_fu_451_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln47_2_fu_447_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln47_6_fu_459_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln47_fu_463_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln47_5_fu_476_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln47_5_fu_476_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln47_5_fu_476_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln47_14_fu_489_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln47_14_fu_489_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln47_14_fu_489_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_12_fu_499_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_13_fu_511_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln47_53_fu_507_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln47_54_fu_519_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln47_6_fu_523_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_14_fu_533_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_15_fu_544_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln47_55_fu_540_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln47_56_fu_551_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln47_7_fu_555_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_2_fu_574_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_3_fu_585_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln47_10_fu_581_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln47_18_fu_592_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln47_1_fu_596_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_4_fu_606_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_5_fu_617_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln47_30_fu_613_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln47_38_fu_624_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln47_2_fu_628_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_6_fu_638_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_7_fu_650_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln47_42_fu_646_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln47_46_fu_658_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln47_3_fu_662_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_8_fu_672_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_9_fu_683_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln47_49_fu_679_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln47_50_fu_690_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln47_4_fu_694_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_887_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln47_11_fu_634_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln93_1_fu_704_p2 : STD_LOGIC_VECTOR (16 downto 0);
    attribute use_dsp48 : string;
    attribute use_dsp48 of add_ln93_1_fu_704_p2 : signal is "no";
    signal grp_fu_860_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln47_31_fu_700_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln93_3_fu_713_p2 : STD_LOGIC_VECTOR (16 downto 0);
    attribute use_dsp48 of add_ln93_3_fu_713_p2 : signal is "no";
    signal zext_ln93_2_fu_718_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln93_1_fu_709_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_851_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln47_7_fu_602_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln93_6_fu_728_p2 : STD_LOGIC_VECTOR (16 downto 0);
    attribute use_dsp48 of add_ln93_6_fu_728_p2 : signal is "no";
    signal grp_fu_878_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln47_19_fu_668_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln93_8_fu_737_p2 : STD_LOGIC_VECTOR (16 downto 0);
    attribute use_dsp48 of add_ln93_8_fu_737_p2 : signal is "no";
    signal zext_ln93_5_fu_742_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln93_4_fu_733_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_869_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_896_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln93_9_fu_755_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln93_8_fu_752_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_905_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_923_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_914_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln93_13_fu_770_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln93_12_fu_767_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln93_20_fu_773_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln93_14_fu_779_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal zext_ln93_11_fu_764_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal zext_ln93_6_fu_792_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal zext_ln93_3_fu_789_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal add_ln93_10_fu_795_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal zext_ln93_15_fu_808_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal zext_ln93_10_fu_805_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal add_ln93_22_fu_811_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal zext_ln93_7_fu_801_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal add_ln93_23_fu_817_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal grp_fu_827_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_827_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_827_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_835_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_835_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_835_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_843_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_843_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_843_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_851_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_851_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_851_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_860_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_860_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_860_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_869_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_869_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_878_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_878_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_878_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_887_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_887_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_887_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_896_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_896_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_905_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_905_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_914_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_914_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_914_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_923_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_923_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_923_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_827_ce : STD_LOGIC;
    signal grp_fu_835_ce : STD_LOGIC;
    signal grp_fu_843_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal grp_fu_827_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_827_p20 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_835_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_835_p20 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_843_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_843_p20 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_851_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_851_p20 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_860_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_860_p20 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_869_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_878_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_878_p20 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_887_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_887_p20 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_896_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_905_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_914_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_914_p20 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_923_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_923_p20 : STD_LOGIC_VECTOR (16 downto 0);
    signal mul_ln47_10_fu_329_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln47_12_fu_342_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln47_14_fu_489_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln47_5_fu_476_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln47_fu_429_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component GaussianFilter_mul_8ns_9ns_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (8 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component GaussianFilter_mac_muladd_8ns_8ns_16ns_17_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (16 downto 0) );
    end component;


    component GaussianFilter_mac_muladd_8ns_8ns_17ns_17_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (16 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (16 downto 0) );
    end component;


    component GaussianFilter_CTRL_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_continue : OUT STD_LOGIC;
        ap_idle : IN STD_LOGIC;
        ap_return : IN STD_LOGIC_VECTOR (31 downto 0);
        data_in_0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        data_in_1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        data_in_2 : OUT STD_LOGIC_VECTOR (7 downto 0);
        data_in_3 : OUT STD_LOGIC_VECTOR (7 downto 0);
        data_in_4 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    CTRL_s_axi_U : component GaussianFilter_CTRL_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CTRL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CTRL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_CTRL_AWVALID,
        AWREADY => s_axi_CTRL_AWREADY,
        AWADDR => s_axi_CTRL_AWADDR,
        WVALID => s_axi_CTRL_WVALID,
        WREADY => s_axi_CTRL_WREADY,
        WDATA => s_axi_CTRL_WDATA,
        WSTRB => s_axi_CTRL_WSTRB,
        ARVALID => s_axi_CTRL_ARVALID,
        ARREADY => s_axi_CTRL_ARREADY,
        ARADDR => s_axi_CTRL_ARADDR,
        RVALID => s_axi_CTRL_RVALID,
        RREADY => s_axi_CTRL_RREADY,
        RDATA => s_axi_CTRL_RDATA,
        RRESP => s_axi_CTRL_RRESP,
        BVALID => s_axi_CTRL_BVALID,
        BREADY => s_axi_CTRL_BREADY,
        BRESP => s_axi_CTRL_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_continue => ap_continue,
        ap_idle => ap_idle,
        ap_return => ap_return,
        data_in_0 => data_in_0,
        data_in_1 => data_in_1,
        data_in_2 => data_in_2,
        data_in_3 => data_in_3,
        data_in_4 => data_in_4);

    mul_8ns_9ns_16_1_1_U1 : component GaussianFilter_mul_8ns_9ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 9,
        dout_WIDTH => 16)
    port map (
        din0 => mul_ln47_10_fu_329_p0,
        din1 => mul_ln47_10_fu_329_p1,
        dout => mul_ln47_10_fu_329_p2);

    mul_8ns_9ns_16_1_1_U2 : component GaussianFilter_mul_8ns_9ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 9,
        dout_WIDTH => 16)
    port map (
        din0 => mul_ln47_12_fu_342_p0,
        din1 => mul_ln47_12_fu_342_p1,
        dout => mul_ln47_12_fu_342_p2);

    mul_8ns_9ns_16_1_1_U3 : component GaussianFilter_mul_8ns_9ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 9,
        dout_WIDTH => 16)
    port map (
        din0 => mul_ln47_fu_429_p0,
        din1 => mul_ln47_fu_429_p1,
        dout => mul_ln47_fu_429_p2);

    mul_8ns_9ns_16_1_1_U4 : component GaussianFilter_mul_8ns_9ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 9,
        dout_WIDTH => 16)
    port map (
        din0 => mul_ln47_5_fu_476_p0,
        din1 => mul_ln47_5_fu_476_p1,
        dout => mul_ln47_5_fu_476_p2);

    mul_8ns_9ns_16_1_1_U5 : component GaussianFilter_mul_8ns_9ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 9,
        dout_WIDTH => 16)
    port map (
        din0 => mul_ln47_14_fu_489_p0,
        din1 => mul_ln47_14_fu_489_p1,
        dout => mul_ln47_14_fu_489_p2);

    mac_muladd_8ns_8ns_16ns_17_4_1_U6 : component GaussianFilter_mac_muladd_8ns_8ns_16ns_17_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_827_p0,
        din1 => grp_fu_827_p1,
        din2 => grp_fu_827_p2,
        ce => grp_fu_827_ce,
        dout => grp_fu_827_p3);

    mac_muladd_8ns_8ns_16ns_17_4_1_U7 : component GaussianFilter_mac_muladd_8ns_8ns_16ns_17_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_835_p0,
        din1 => grp_fu_835_p1,
        din2 => grp_fu_835_p2,
        ce => grp_fu_835_ce,
        dout => grp_fu_835_p3);

    mac_muladd_8ns_8ns_16ns_17_4_1_U8 : component GaussianFilter_mac_muladd_8ns_8ns_16ns_17_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_843_p0,
        din1 => grp_fu_843_p1,
        din2 => grp_fu_843_p2,
        ce => grp_fu_843_ce,
        dout => grp_fu_843_p3);

    mac_muladd_8ns_8ns_16ns_17_4_1_U9 : component GaussianFilter_mac_muladd_8ns_8ns_16ns_17_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_851_p0,
        din1 => grp_fu_851_p1,
        din2 => grp_fu_851_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_851_p3);

    mac_muladd_8ns_8ns_16ns_17_4_1_U10 : component GaussianFilter_mac_muladd_8ns_8ns_16ns_17_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_860_p0,
        din1 => grp_fu_860_p1,
        din2 => grp_fu_860_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_860_p3);

    mac_muladd_8ns_8ns_17ns_17_4_1_U11 : component GaussianFilter_mac_muladd_8ns_8ns_17ns_17_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 17,
        dout_WIDTH => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_869_p0,
        din1 => grp_fu_869_p1,
        din2 => grp_fu_835_p3,
        ce => ap_const_logic_1,
        dout => grp_fu_869_p3);

    mac_muladd_8ns_8ns_16ns_17_4_1_U12 : component GaussianFilter_mac_muladd_8ns_8ns_16ns_17_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_878_p0,
        din1 => grp_fu_878_p1,
        din2 => grp_fu_878_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_878_p3);

    mac_muladd_8ns_8ns_16ns_17_4_1_U13 : component GaussianFilter_mac_muladd_8ns_8ns_16ns_17_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_887_p0,
        din1 => grp_fu_887_p1,
        din2 => grp_fu_887_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_887_p3);

    mac_muladd_8ns_8ns_17ns_17_4_1_U14 : component GaussianFilter_mac_muladd_8ns_8ns_17ns_17_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 17,
        dout_WIDTH => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_896_p0,
        din1 => grp_fu_896_p1,
        din2 => grp_fu_827_p3,
        ce => ap_const_logic_1,
        dout => grp_fu_896_p3);

    mac_muladd_8ns_8ns_17ns_17_4_1_U15 : component GaussianFilter_mac_muladd_8ns_8ns_17ns_17_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 17,
        dout_WIDTH => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_905_p0,
        din1 => grp_fu_905_p1,
        din2 => grp_fu_843_p3,
        ce => ap_const_logic_1,
        dout => grp_fu_905_p3);

    mac_muladd_8ns_8ns_16ns_17_4_1_U16 : component GaussianFilter_mac_muladd_8ns_8ns_16ns_17_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_914_p0,
        din1 => grp_fu_914_p1,
        din2 => grp_fu_914_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_914_p3);

    mac_muladd_8ns_8ns_16ns_17_4_1_U17 : component GaussianFilter_mac_muladd_8ns_8ns_16ns_17_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_923_p0,
        din1 => grp_fu_923_p1,
        din2 => grp_fu_923_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_923_p3);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_rst_n_inv_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_rst_n_inv <= ap_rst_reg_1;
        end if;
    end process;

    ap_rst_reg_1_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_rst_reg_1 <= ap_rst_reg_2;
        end if;
    end process;

    ap_rst_reg_2_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
                        ap_rst_reg_2 <= not(ap_rst_n);
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                add_ln93_15_reg_1126 <= add_ln93_15_fu_758_p2;
                add_ln93_21_reg_1131 <= add_ln93_21_fu_783_p2;
                add_ln93_4_reg_1116 <= add_ln93_4_fu_722_p2;
                add_ln93_9_reg_1121 <= add_ln93_9_fu_746_p2;
                p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_3 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_2_load_reg_969;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                data_in_0_read_reg_1038 <= data_in_0;
                data_in_4_read_reg_1032 <= data_in_4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                data_in_1_read_reg_1065 <= data_in_1;
                data_in_3_read_reg_1059 <= data_in_3;
                p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_0 <= data_in_0_read_reg_1038;
                p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_1 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_0;
                p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_0 <= data_in_1;
                p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_0 <= data_in_3;
                p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_0 <= data_in_4_read_reg_1032;
                p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_1 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_2 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_1;
                p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_2_load_reg_963 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_2;
                p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_3 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_2;
                p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_1 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_0;
                p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_2 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_1;
                p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_2_load_reg_969 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_2;
                p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_0 <= data_in_2;
                p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_2 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_1_load_reg_942;
                p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_3 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_2;
                p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_3_load_reg_975 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_3;
                p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_2 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_1;
                p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_2_load_reg_981 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_2;
                p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_3 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_1 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_0;
                p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_1_load_reg_937 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_1;
                p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_2 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_1;
                p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_3 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_2;
                p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_3_load_reg_932 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_3;
                p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_1 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_0;
                p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_1_load_reg_942 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    add_ln47_1_fu_596_p2 <= std_logic_vector(unsigned(zext_ln47_10_fu_581_p1) + unsigned(zext_ln47_18_fu_592_p1));
    add_ln47_2_fu_628_p2 <= std_logic_vector(unsigned(zext_ln47_30_fu_613_p1) + unsigned(zext_ln47_38_fu_624_p1));
    add_ln47_3_fu_662_p2 <= std_logic_vector(unsigned(zext_ln47_42_fu_646_p1) + unsigned(zext_ln47_46_fu_658_p1));
    add_ln47_4_fu_694_p2 <= std_logic_vector(unsigned(zext_ln47_49_fu_679_p1) + unsigned(zext_ln47_50_fu_690_p1));
    add_ln47_5_fu_374_p2 <= std_logic_vector(unsigned(zext_ln47_51_fu_359_p1) + unsigned(zext_ln47_52_fu_370_p1));
    add_ln47_6_fu_523_p2 <= std_logic_vector(unsigned(zext_ln47_53_fu_507_p1) + unsigned(zext_ln47_54_fu_519_p1));
    add_ln47_7_fu_555_p2 <= std_logic_vector(unsigned(zext_ln47_55_fu_540_p1) + unsigned(zext_ln47_56_fu_551_p1));
    add_ln47_fu_463_p2 <= std_logic_vector(unsigned(zext_ln47_2_fu_447_p1) + unsigned(zext_ln47_6_fu_459_p1));
    add_ln93_10_fu_795_p2 <= std_logic_vector(unsigned(zext_ln93_6_fu_792_p1) + unsigned(zext_ln93_3_fu_789_p1));
    add_ln93_15_fu_758_p2 <= std_logic_vector(unsigned(zext_ln93_9_fu_755_p1) + unsigned(zext_ln93_8_fu_752_p1));
    add_ln93_1_fu_704_p2 <= std_logic_vector(unsigned(grp_fu_887_p3) + unsigned(zext_ln47_11_fu_634_p1));
    add_ln93_20_fu_773_p2 <= std_logic_vector(unsigned(zext_ln93_13_fu_770_p1) + unsigned(zext_ln93_12_fu_767_p1));
    add_ln93_21_fu_783_p2 <= std_logic_vector(unsigned(zext_ln93_14_fu_779_p1) + unsigned(zext_ln93_11_fu_764_p1));
    add_ln93_22_fu_811_p2 <= std_logic_vector(unsigned(zext_ln93_15_fu_808_p1) + unsigned(zext_ln93_10_fu_805_p1));
    add_ln93_23_fu_817_p2 <= std_logic_vector(unsigned(add_ln93_22_fu_811_p2) + unsigned(zext_ln93_7_fu_801_p1));
    add_ln93_3_fu_713_p2 <= std_logic_vector(unsigned(grp_fu_860_p3) + unsigned(zext_ln47_31_fu_700_p1));
    add_ln93_4_fu_722_p2 <= std_logic_vector(unsigned(zext_ln93_2_fu_718_p1) + unsigned(zext_ln93_1_fu_709_p1));
    add_ln93_6_fu_728_p2 <= std_logic_vector(unsigned(grp_fu_851_p3) + unsigned(zext_ln47_7_fu_602_p1));
    add_ln93_8_fu_737_p2 <= std_logic_vector(unsigned(grp_fu_878_p3) + unsigned(zext_ln47_19_fu_668_p1));
    add_ln93_9_fu_746_p2 <= std_logic_vector(unsigned(zext_ln93_5_fu_742_p1) + unsigned(zext_ln93_4_fu_733_p1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln93_23_fu_817_p2),32));

    grp_fu_827_ce_assign_proc : process(ap_CS_fsm_state1, ap_block_state1, ap_CS_fsm_state5, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5) or ((ap_const_boolean_1 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            grp_fu_827_ce <= ap_const_logic_0;
        else 
            grp_fu_827_ce <= ap_const_logic_1;
        end if; 
    end process;

    grp_fu_827_p0 <= grp_fu_827_p00(8 - 1 downto 0);
    grp_fu_827_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_0),16));
    grp_fu_827_p1 <= ap_const_lv16_AE(8 - 1 downto 0);
    grp_fu_827_p2 <= grp_fu_827_p20(16 - 1 downto 0);
    grp_fu_827_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln47_5_fu_374_p2),17));

    grp_fu_835_ce_assign_proc : process(ap_CS_fsm_state1, ap_block_state1, ap_CS_fsm_state5, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5) or ((ap_const_boolean_1 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            grp_fu_835_ce <= ap_const_logic_0;
        else 
            grp_fu_835_ce <= ap_const_logic_1;
        end if; 
    end process;

    grp_fu_835_p0 <= grp_fu_835_p00(8 - 1 downto 0);
    grp_fu_835_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_2),16));
    grp_fu_835_p1 <= ap_const_lv16_AE(8 - 1 downto 0);
    grp_fu_835_p2 <= grp_fu_835_p20(16 - 1 downto 0);
    grp_fu_835_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln47_10_fu_329_p2),17));

    grp_fu_843_ce_assign_proc : process(ap_CS_fsm_state1, ap_block_state1, ap_CS_fsm_state5, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5) or ((ap_const_boolean_1 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            grp_fu_843_ce <= ap_const_logic_0;
        else 
            grp_fu_843_ce <= ap_const_logic_1;
        end if; 
    end process;

    grp_fu_843_p0 <= grp_fu_843_p00(8 - 1 downto 0);
    grp_fu_843_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_0),16));
    grp_fu_843_p1 <= ap_const_lv16_AA(8 - 1 downto 0);
    grp_fu_843_p2 <= grp_fu_843_p20(16 - 1 downto 0);
    grp_fu_843_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln47_12_fu_342_p2),17));
    grp_fu_851_p0 <= grp_fu_851_p00(8 - 1 downto 0);
    grp_fu_851_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_1),16));
    grp_fu_851_p1 <= ap_const_lv16_A4(8 - 1 downto 0);
    grp_fu_851_p2 <= grp_fu_851_p20(16 - 1 downto 0);
    grp_fu_851_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln47_fu_463_p2),17));
    grp_fu_860_p0 <= grp_fu_860_p00(8 - 1 downto 0);
    grp_fu_860_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_3),16));
    grp_fu_860_p1 <= ap_const_lv16_97(8 - 1 downto 0);
    grp_fu_860_p2 <= grp_fu_860_p20(16 - 1 downto 0);
    grp_fu_860_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln47_14_fu_489_p2),17));
    grp_fu_869_p0 <= grp_fu_869_p00(8 - 1 downto 0);
    grp_fu_869_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_0),16));
    grp_fu_869_p1 <= ap_const_lv16_AA(8 - 1 downto 0);
    grp_fu_878_p0 <= grp_fu_878_p00(8 - 1 downto 0);
    grp_fu_878_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_1),16));
    grp_fu_878_p1 <= ap_const_lv16_AE(8 - 1 downto 0);
    grp_fu_878_p2 <= grp_fu_878_p20(16 - 1 downto 0);
    grp_fu_878_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln47_5_fu_476_p2),17));
    grp_fu_887_p0 <= grp_fu_887_p00(8 - 1 downto 0);
    grp_fu_887_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(data_in_2),16));
    grp_fu_887_p1 <= ap_const_lv16_A4(8 - 1 downto 0);
    grp_fu_887_p2 <= grp_fu_887_p20(16 - 1 downto 0);
    grp_fu_887_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln47_fu_429_p2),17));
    grp_fu_896_p0 <= grp_fu_896_p00(8 - 1 downto 0);
    grp_fu_896_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_1_load_reg_937),16));
    grp_fu_896_p1 <= ap_const_lv16_B1(8 - 1 downto 0);
    grp_fu_905_p0 <= grp_fu_905_p00(8 - 1 downto 0);
    grp_fu_905_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_2),16));
    grp_fu_905_p1 <= ap_const_lv16_AA(8 - 1 downto 0);
    grp_fu_914_p0 <= grp_fu_914_p00(8 - 1 downto 0);
    grp_fu_914_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_1),16));
    grp_fu_914_p1 <= ap_const_lv16_A4(8 - 1 downto 0);
    grp_fu_914_p2 <= grp_fu_914_p20(16 - 1 downto 0);
    grp_fu_914_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln47_6_fu_523_p2),17));
    grp_fu_923_p0 <= grp_fu_923_p00(8 - 1 downto 0);
    grp_fu_923_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_3),16));
    grp_fu_923_p1 <= ap_const_lv16_97(8 - 1 downto 0);
    grp_fu_923_p2 <= grp_fu_923_p20(16 - 1 downto 0);
    grp_fu_923_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln47_7_fu_555_p2),17));
    mul_ln47_10_fu_329_p0 <= mul_ln47_10_fu_329_p00(8 - 1 downto 0);
    mul_ln47_10_fu_329_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_3_load_reg_932),16));
    mul_ln47_10_fu_329_p1 <= ap_const_lv16_A4(9 - 1 downto 0);
    mul_ln47_12_fu_342_p0 <= mul_ln47_12_fu_342_p00(8 - 1 downto 0);
    mul_ln47_12_fu_342_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_1_load_reg_942),16));
    mul_ln47_12_fu_342_p1 <= ap_const_lv16_AE(9 - 1 downto 0);
    mul_ln47_14_fu_489_p0 <= mul_ln47_14_fu_489_p00(8 - 1 downto 0);
    mul_ln47_14_fu_489_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(data_in_4_read_reg_1032),16));
    mul_ln47_14_fu_489_p1 <= ap_const_lv16_97(9 - 1 downto 0);
    mul_ln47_5_fu_476_p0 <= mul_ln47_5_fu_476_p00(8 - 1 downto 0);
    mul_ln47_5_fu_476_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_2_load_reg_969),16));
    mul_ln47_5_fu_476_p1 <= ap_const_lv16_AA(9 - 1 downto 0);
    mul_ln47_fu_429_p0 <= mul_ln47_fu_429_p00(8 - 1 downto 0);
    mul_ln47_fu_429_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(data_in_0_read_reg_1038),16));
    mul_ln47_fu_429_p1 <= ap_const_lv16_97(9 - 1 downto 0);
    tmp_10_fu_352_p3 <= (p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_3_load_reg_975 & ap_const_lv7_0);
    tmp_11_fu_363_p3 <= (p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_3_load_reg_975 & ap_const_lv5_0);
    tmp_12_fu_499_p3 <= (p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_0 & ap_const_lv7_0);
    tmp_13_fu_511_p3 <= (p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_0 & ap_const_lv5_0);
    tmp_14_fu_533_p3 <= (p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_2_load_reg_981 & ap_const_lv7_0);
    tmp_15_fu_544_p3 <= (p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_2_load_reg_981 & ap_const_lv5_0);
    tmp_1_fu_451_p3 <= (p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_0 & ap_const_lv5_0);
    tmp_2_fu_574_p3 <= (p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_2_load_reg_963 & ap_const_lv7_0);
    tmp_3_fu_585_p3 <= (p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_2_load_reg_963 & ap_const_lv5_0);
    tmp_4_fu_606_p3 <= (data_in_1_read_reg_1065 & ap_const_lv7_0);
    tmp_5_fu_617_p3 <= (data_in_1_read_reg_1065 & ap_const_lv5_0);
    tmp_6_fu_638_p3 <= (p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_3 & ap_const_lv7_0);
    tmp_7_fu_650_p3 <= (p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_3 & ap_const_lv5_0);
    tmp_8_fu_672_p3 <= (data_in_3_read_reg_1059 & ap_const_lv7_0);
    tmp_9_fu_683_p3 <= (data_in_3_read_reg_1059 & ap_const_lv5_0);
    tmp_fu_439_p3 <= (p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_0 & ap_const_lv7_0);
    zext_ln47_10_fu_581_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_fu_574_p3),16));
    zext_ln47_11_fu_634_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln47_2_fu_628_p2),17));
    zext_ln47_18_fu_592_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_fu_585_p3),16));
    zext_ln47_19_fu_668_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln47_3_fu_662_p2),17));
    zext_ln47_2_fu_447_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_439_p3),16));
    zext_ln47_30_fu_613_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_4_fu_606_p3),16));
    zext_ln47_31_fu_700_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln47_4_fu_694_p2),17));
    zext_ln47_38_fu_624_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_5_fu_617_p3),16));
    zext_ln47_42_fu_646_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_6_fu_638_p3),16));
    zext_ln47_46_fu_658_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_7_fu_650_p3),16));
    zext_ln47_49_fu_679_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_8_fu_672_p3),16));
    zext_ln47_50_fu_690_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_9_fu_683_p3),16));
    zext_ln47_51_fu_359_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_10_fu_352_p3),16));
    zext_ln47_52_fu_370_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_11_fu_363_p3),16));
    zext_ln47_53_fu_507_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_12_fu_499_p3),16));
    zext_ln47_54_fu_519_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_13_fu_511_p3),16));
    zext_ln47_55_fu_540_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_14_fu_533_p3),16));
    zext_ln47_56_fu_551_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_15_fu_544_p3),16));
    zext_ln47_6_fu_459_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_451_p3),16));
    zext_ln47_7_fu_602_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln47_1_fu_596_p2),17));
    zext_ln93_10_fu_805_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln93_15_reg_1126),20));
    zext_ln93_11_fu_764_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_905_p3),19));
    zext_ln93_12_fu_767_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_923_p3),18));
    zext_ln93_13_fu_770_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_914_p3),18));
    zext_ln93_14_fu_779_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln93_20_fu_773_p2),19));
    zext_ln93_15_fu_808_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln93_21_reg_1131),20));
    zext_ln93_1_fu_709_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln93_1_fu_704_p2),18));
    zext_ln93_2_fu_718_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln93_3_fu_713_p2),18));
    zext_ln93_3_fu_789_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln93_4_reg_1116),19));
    zext_ln93_4_fu_733_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln93_6_fu_728_p2),18));
    zext_ln93_5_fu_742_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln93_8_fu_737_p2),18));
    zext_ln93_6_fu_792_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln93_9_reg_1121),19));
    zext_ln93_7_fu_801_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln93_10_fu_795_p2),20));
    zext_ln93_8_fu_752_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_869_p3),18));
    zext_ln93_9_fu_755_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_896_p3),18));
end behav;
