-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ImgSharpeningFilter is
generic (
    C_S_AXI_CTRL_ADDR_WIDTH : INTEGER := 6;
    C_S_AXI_CTRL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    s_axi_CTRL_AWVALID : IN STD_LOGIC;
    s_axi_CTRL_AWREADY : OUT STD_LOGIC;
    s_axi_CTRL_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_WVALID : IN STD_LOGIC;
    s_axi_CTRL_WREADY : OUT STD_LOGIC;
    s_axi_CTRL_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH/8-1 downto 0);
    s_axi_CTRL_ARVALID : IN STD_LOGIC;
    s_axi_CTRL_ARREADY : OUT STD_LOGIC;
    s_axi_CTRL_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_RVALID : OUT STD_LOGIC;
    s_axi_CTRL_RREADY : IN STD_LOGIC;
    s_axi_CTRL_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_CTRL_BVALID : OUT STD_LOGIC;
    s_axi_CTRL_BREADY : IN STD_LOGIC;
    s_axi_CTRL_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of ImgSharpeningFilter is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "ImgSharpeningFilter_ImgSharpeningFilter,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z007s-clg400-1,HLS_INPUT_CLOCK=8.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.301000,HLS_SYN_LAT=2,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=153,HLS_SYN_LUT=228,HLS_VERSION=2025_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";

attribute shreg_extract : string;
    signal ap_rst_reg_2 : STD_LOGIC := '1';
attribute shreg_extract of ap_rst_reg_2 : signal is "no";
    signal ap_rst_reg_1 : STD_LOGIC := '1';
attribute shreg_extract of ap_rst_reg_1 : signal is "no";
    signal ap_rst_n_inv : STD_LOGIC := '1';
attribute shreg_extract of ap_rst_n_inv : signal is "no";
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_continue : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal data_in_0 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_in_1 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_in_2 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_ZZ19ImgSharpeningFilter7ap_uintILi8EES0_S0_E13data_in_array_0_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ19ImgSharpeningFilter7ap_uintILi8EES0_S0_E13data_in_array_1_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ19ImgSharpeningFilter7ap_uintILi8EES0_S0_E13data_in_array_1_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZ19ImgSharpeningFilter7ap_uintILi8EES0_S0_E13data_in_array_2_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_return : STD_LOGIC_VECTOR (7 downto 0);
    signal data_in_1_read_reg_244 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal add_ln49_fu_98_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln49_reg_249 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_2_reg_254 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal trunc_ln58_fu_216_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln58_reg_259 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal zext_ln38_1_fu_90_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln38_3_fu_94_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_fu_139_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln49_3_fu_147_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln38_2_fu_131_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln49_2_fu_151_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln49_1_fu_161_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln38_fu_127_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln49_1_fu_164_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln43_fu_157_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln49_2_fu_170_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal AddRes_3_fu_174_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln49_fu_135_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal AddRes_fu_180_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_1_fu_190_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln43_fu_186_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal AddRes_2_fu_198_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln55_fu_232_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component ImgSharpeningFilter_CTRL_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_continue : OUT STD_LOGIC;
        ap_idle : IN STD_LOGIC;
        ap_return : IN STD_LOGIC_VECTOR (7 downto 0);
        data_in_0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        data_in_1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        data_in_2 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    CTRL_s_axi_U : component ImgSharpeningFilter_CTRL_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CTRL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CTRL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_CTRL_AWVALID,
        AWREADY => s_axi_CTRL_AWREADY,
        AWADDR => s_axi_CTRL_AWADDR,
        WVALID => s_axi_CTRL_WVALID,
        WREADY => s_axi_CTRL_WREADY,
        WDATA => s_axi_CTRL_WDATA,
        WSTRB => s_axi_CTRL_WSTRB,
        ARVALID => s_axi_CTRL_ARVALID,
        ARREADY => s_axi_CTRL_ARREADY,
        ARADDR => s_axi_CTRL_ARADDR,
        RVALID => s_axi_CTRL_RVALID,
        RREADY => s_axi_CTRL_RREADY,
        RDATA => s_axi_CTRL_RDATA,
        RRESP => s_axi_CTRL_RRESP,
        BVALID => s_axi_CTRL_BVALID,
        BREADY => s_axi_CTRL_BREADY,
        BRESP => s_axi_CTRL_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_continue => ap_continue,
        ap_idle => ap_idle,
        ap_return => ap_return,
        data_in_0 => data_in_0,
        data_in_1 => data_in_1,
        data_in_2 => data_in_2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_rst_n_inv_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_rst_n_inv <= ap_rst_reg_1;
        end if;
    end process;

    ap_rst_reg_1_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_rst_reg_1 <= ap_rst_reg_2;
        end if;
    end process;

    ap_rst_reg_2_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
                        ap_rst_reg_2 <= not(ap_rst_n);
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                add_ln49_reg_249 <= add_ln49_fu_98_p2;
                data_in_1_read_reg_244 <= data_in_1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                p_ZZ19ImgSharpeningFilter7ap_uintILi8EES0_S0_E13data_in_array_0_0 <= data_in_0;
                p_ZZ19ImgSharpeningFilter7ap_uintILi8EES0_S0_E13data_in_array_2_0 <= data_in_2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                p_ZZ19ImgSharpeningFilter7ap_uintILi8EES0_S0_E13data_in_array_1_0 <= data_in_1_read_reg_244;
                p_ZZ19ImgSharpeningFilter7ap_uintILi8EES0_S0_E13data_in_array_1_1 <= p_ZZ19ImgSharpeningFilter7ap_uintILi8EES0_S0_E13data_in_array_1_0;
                tmp_2_reg_254 <= AddRes_2_fu_198_p3(10 downto 8);
                trunc_ln58_reg_259 <= trunc_ln58_fu_216_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    AddRes_2_fu_198_p3 <= 
        ap_const_lv11_0 when (tmp_1_fu_190_p3(0) = '1') else 
        trunc_ln43_fu_186_p1;
    AddRes_3_fu_174_p2 <= std_logic_vector(unsigned(zext_ln43_fu_157_p1) - unsigned(zext_ln49_2_fu_170_p1));
    AddRes_fu_180_p2 <= std_logic_vector(unsigned(AddRes_3_fu_174_p2) - unsigned(zext_ln49_fu_135_p1));
    add_ln49_1_fu_164_p2 <= std_logic_vector(unsigned(zext_ln49_1_fu_161_p1) + unsigned(zext_ln38_fu_127_p1));
    add_ln49_2_fu_151_p2 <= std_logic_vector(unsigned(zext_ln49_3_fu_147_p1) + unsigned(zext_ln38_2_fu_131_p1));
    add_ln49_fu_98_p2 <= std_logic_vector(unsigned(zext_ln38_1_fu_90_p1) + unsigned(zext_ln38_3_fu_94_p1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return <= 
        ap_const_lv8_FF when (icmp_ln55_fu_232_p2(0) = '1') else 
        trunc_ln58_reg_259;
    icmp_ln55_fu_232_p2 <= "0" when (tmp_2_reg_254 = ap_const_lv3_0) else "1";
    tmp_1_fu_190_p3 <= AddRes_fu_180_p2(11 downto 11);
    tmp_fu_139_p3 <= (p_ZZ19ImgSharpeningFilter7ap_uintILi8EES0_S0_E13data_in_array_1_0 & ap_const_lv2_0);
    trunc_ln43_fu_186_p1 <= AddRes_fu_180_p2(11 - 1 downto 0);
    trunc_ln58_fu_216_p1 <= AddRes_2_fu_198_p3(8 - 1 downto 0);
    zext_ln38_1_fu_90_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(data_in_1),9));
    zext_ln38_2_fu_131_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_ZZ19ImgSharpeningFilter7ap_uintILi8EES0_S0_E13data_in_array_1_0),11));
    zext_ln38_3_fu_94_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_ZZ19ImgSharpeningFilter7ap_uintILi8EES0_S0_E13data_in_array_1_1),9));
    zext_ln38_fu_127_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_ZZ19ImgSharpeningFilter7ap_uintILi8EES0_S0_E13data_in_array_0_0),10));
    zext_ln43_fu_157_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln49_2_fu_151_p2),12));
    zext_ln49_1_fu_161_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln49_reg_249),10));
    zext_ln49_2_fu_170_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln49_1_fu_164_p2),12));
    zext_ln49_3_fu_147_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_139_p3),11));
    zext_ln49_fu_135_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_ZZ19ImgSharpeningFilter7ap_uintILi8EES0_S0_E13data_in_array_2_0),12));
end behav;
