// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="GaussianFilter_GaussianFilter,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z007s-clg400-1,HLS_INPUT_CLOCK=8.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.450000,HLS_SYN_LAT=5,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=469,HLS_SYN_LUT=959,HLS_VERSION=2025_1}" *)

module GaussianFilter (
        ap_clk,
        ap_rst_n,
        s_axi_CTRL_AWVALID,
        s_axi_CTRL_AWREADY,
        s_axi_CTRL_AWADDR,
        s_axi_CTRL_WVALID,
        s_axi_CTRL_WREADY,
        s_axi_CTRL_WDATA,
        s_axi_CTRL_WSTRB,
        s_axi_CTRL_ARVALID,
        s_axi_CTRL_ARREADY,
        s_axi_CTRL_ARADDR,
        s_axi_CTRL_RVALID,
        s_axi_CTRL_RREADY,
        s_axi_CTRL_RDATA,
        s_axi_CTRL_RRESP,
        s_axi_CTRL_BVALID,
        s_axi_CTRL_BREADY,
        s_axi_CTRL_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;
parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   s_axi_CTRL_AWVALID;
output   s_axi_CTRL_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_AWADDR;
input   s_axi_CTRL_WVALID;
output   s_axi_CTRL_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_CTRL_WSTRB;
input   s_axi_CTRL_ARVALID;
output   s_axi_CTRL_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_ARADDR;
output   s_axi_CTRL_RVALID;
input   s_axi_CTRL_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_RDATA;
output  [1:0] s_axi_CTRL_RRESP;
output   s_axi_CTRL_BVALID;
input   s_axi_CTRL_BREADY;
output  [1:0] s_axi_CTRL_BRESP;
output   interrupt;

(* shreg_extract = "no" *) reg    ap_rst_reg_2;
(* shreg_extract = "no" *) reg    ap_rst_reg_1;
(* shreg_extract = "no" *) reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
wire    ap_continue;
reg    ap_done_reg;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [7:0] data_in_0;
wire   [7:0] data_in_1;
wire   [7:0] data_in_2;
wire   [7:0] data_in_3;
wire   [7:0] data_in_4;
reg   [7:0] p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_3;
reg   [7:0] p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_2;
reg   [7:0] p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_1;
reg   [7:0] p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_0;
reg   [7:0] p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_3;
reg   [7:0] p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_2;
reg   [7:0] p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_1;
reg   [7:0] p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_0;
reg   [7:0] p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_3;
reg   [7:0] p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_2;
reg   [7:0] p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_1;
reg   [7:0] p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_0;
reg   [7:0] p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_3;
reg   [7:0] p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_2;
reg   [7:0] p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_1;
reg   [7:0] p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_0;
reg   [7:0] p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_3;
reg   [7:0] p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_2;
reg   [7:0] p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_1;
reg   [7:0] p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_0;
wire   [31:0] ap_return;
reg   [7:0] p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_3_load_reg_932;
reg    ap_block_state1;
reg   [7:0] p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_1_load_reg_937;
reg   [7:0] p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_1_load_reg_942;
reg   [7:0] p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_2_load_reg_963;
wire    ap_CS_fsm_state2;
reg   [7:0] p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_2_load_reg_969;
reg   [7:0] p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_3_load_reg_975;
reg   [7:0] p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_2_load_reg_981;
reg   [7:0] data_in_4_read_reg_1032;
wire    ap_CS_fsm_state3;
reg   [7:0] data_in_0_read_reg_1038;
reg   [7:0] data_in_3_read_reg_1059;
wire    ap_CS_fsm_state4;
reg   [7:0] data_in_1_read_reg_1065;
wire   [16:0] grp_fu_835_p3;
wire   [16:0] grp_fu_827_p3;
wire   [16:0] grp_fu_843_p3;
wire   [17:0] add_ln93_4_fu_722_p2;
reg   [17:0] add_ln93_4_reg_1116;
wire    ap_CS_fsm_state5;
wire   [17:0] add_ln93_9_fu_746_p2;
reg   [17:0] add_ln93_9_reg_1121;
wire   [17:0] add_ln93_15_fu_758_p2;
reg   [17:0] add_ln93_15_reg_1126;
wire   [18:0] add_ln93_21_fu_783_p2;
reg   [18:0] add_ln93_21_reg_1131;
wire   [7:0] mul_ln47_10_fu_329_p0;
wire   [8:0] mul_ln47_10_fu_329_p1;
wire   [15:0] mul_ln47_10_fu_329_p2;
wire   [7:0] mul_ln47_12_fu_342_p0;
wire   [8:0] mul_ln47_12_fu_342_p1;
wire   [15:0] mul_ln47_12_fu_342_p2;
wire   [14:0] tmp_10_fu_352_p3;
wire   [12:0] tmp_11_fu_363_p3;
wire   [15:0] zext_ln47_51_fu_359_p1;
wire   [15:0] zext_ln47_52_fu_370_p1;
wire   [15:0] add_ln47_5_fu_374_p2;
wire   [7:0] mul_ln47_fu_429_p0;
wire   [8:0] mul_ln47_fu_429_p1;
wire   [15:0] mul_ln47_fu_429_p2;
wire   [14:0] tmp_fu_439_p3;
wire   [12:0] tmp_1_fu_451_p3;
wire   [15:0] zext_ln47_2_fu_447_p1;
wire   [15:0] zext_ln47_6_fu_459_p1;
wire   [15:0] add_ln47_fu_463_p2;
wire   [7:0] mul_ln47_5_fu_476_p0;
wire   [8:0] mul_ln47_5_fu_476_p1;
wire   [15:0] mul_ln47_5_fu_476_p2;
wire   [7:0] mul_ln47_14_fu_489_p0;
wire   [8:0] mul_ln47_14_fu_489_p1;
wire   [15:0] mul_ln47_14_fu_489_p2;
wire   [14:0] tmp_12_fu_499_p3;
wire   [12:0] tmp_13_fu_511_p3;
wire   [15:0] zext_ln47_53_fu_507_p1;
wire   [15:0] zext_ln47_54_fu_519_p1;
wire   [15:0] add_ln47_6_fu_523_p2;
wire   [14:0] tmp_14_fu_533_p3;
wire   [12:0] tmp_15_fu_544_p3;
wire   [15:0] zext_ln47_55_fu_540_p1;
wire   [15:0] zext_ln47_56_fu_551_p1;
wire   [15:0] add_ln47_7_fu_555_p2;
wire   [14:0] tmp_2_fu_574_p3;
wire   [12:0] tmp_3_fu_585_p3;
wire   [15:0] zext_ln47_10_fu_581_p1;
wire   [15:0] zext_ln47_18_fu_592_p1;
wire   [15:0] add_ln47_1_fu_596_p2;
wire   [14:0] tmp_4_fu_606_p3;
wire   [12:0] tmp_5_fu_617_p3;
wire   [15:0] zext_ln47_30_fu_613_p1;
wire   [15:0] zext_ln47_38_fu_624_p1;
wire   [15:0] add_ln47_2_fu_628_p2;
wire   [14:0] tmp_6_fu_638_p3;
wire   [12:0] tmp_7_fu_650_p3;
wire   [15:0] zext_ln47_42_fu_646_p1;
wire   [15:0] zext_ln47_46_fu_658_p1;
wire   [15:0] add_ln47_3_fu_662_p2;
wire   [14:0] tmp_8_fu_672_p3;
wire   [12:0] tmp_9_fu_683_p3;
wire   [15:0] zext_ln47_49_fu_679_p1;
wire   [15:0] zext_ln47_50_fu_690_p1;
wire   [15:0] add_ln47_4_fu_694_p2;
wire   [16:0] grp_fu_887_p3;
wire   [16:0] zext_ln47_11_fu_634_p1;
(* use_dsp48 = "no" *) wire   [16:0] add_ln93_1_fu_704_p2;
wire   [16:0] grp_fu_860_p3;
wire   [16:0] zext_ln47_31_fu_700_p1;
(* use_dsp48 = "no" *) wire   [16:0] add_ln93_3_fu_713_p2;
wire   [17:0] zext_ln93_2_fu_718_p1;
wire   [17:0] zext_ln93_1_fu_709_p1;
wire   [16:0] grp_fu_851_p3;
wire   [16:0] zext_ln47_7_fu_602_p1;
(* use_dsp48 = "no" *) wire   [16:0] add_ln93_6_fu_728_p2;
wire   [16:0] grp_fu_878_p3;
wire   [16:0] zext_ln47_19_fu_668_p1;
(* use_dsp48 = "no" *) wire   [16:0] add_ln93_8_fu_737_p2;
wire   [17:0] zext_ln93_5_fu_742_p1;
wire   [17:0] zext_ln93_4_fu_733_p1;
wire   [16:0] grp_fu_869_p3;
wire   [16:0] grp_fu_896_p3;
wire   [17:0] zext_ln93_9_fu_755_p1;
wire   [17:0] zext_ln93_8_fu_752_p1;
wire   [16:0] grp_fu_905_p3;
wire   [16:0] grp_fu_923_p3;
wire   [16:0] grp_fu_914_p3;
wire   [17:0] zext_ln93_13_fu_770_p1;
wire   [17:0] zext_ln93_12_fu_767_p1;
wire   [17:0] add_ln93_20_fu_773_p2;
wire   [18:0] zext_ln93_14_fu_779_p1;
wire   [18:0] zext_ln93_11_fu_764_p1;
wire    ap_CS_fsm_state6;
wire   [18:0] zext_ln93_6_fu_792_p1;
wire   [18:0] zext_ln93_3_fu_789_p1;
wire   [18:0] add_ln93_10_fu_795_p2;
wire   [19:0] zext_ln93_15_fu_808_p1;
wire   [19:0] zext_ln93_10_fu_805_p1;
wire   [19:0] add_ln93_22_fu_811_p2;
wire   [19:0] zext_ln93_7_fu_801_p1;
wire   [19:0] add_ln93_23_fu_817_p2;
wire   [7:0] grp_fu_827_p0;
wire   [7:0] grp_fu_827_p1;
wire   [15:0] grp_fu_827_p2;
wire   [7:0] grp_fu_835_p0;
wire   [7:0] grp_fu_835_p1;
wire   [15:0] grp_fu_835_p2;
wire   [7:0] grp_fu_843_p0;
wire   [7:0] grp_fu_843_p1;
wire   [15:0] grp_fu_843_p2;
wire   [7:0] grp_fu_851_p0;
wire   [7:0] grp_fu_851_p1;
wire   [15:0] grp_fu_851_p2;
wire   [7:0] grp_fu_860_p0;
wire   [7:0] grp_fu_860_p1;
wire   [15:0] grp_fu_860_p2;
wire   [7:0] grp_fu_869_p0;
wire   [7:0] grp_fu_869_p1;
wire   [7:0] grp_fu_878_p0;
wire   [7:0] grp_fu_878_p1;
wire   [15:0] grp_fu_878_p2;
wire   [7:0] grp_fu_887_p0;
wire   [7:0] grp_fu_887_p1;
wire   [15:0] grp_fu_887_p2;
wire   [7:0] grp_fu_896_p0;
wire   [7:0] grp_fu_896_p1;
wire   [7:0] grp_fu_905_p0;
wire   [7:0] grp_fu_905_p1;
wire   [7:0] grp_fu_914_p0;
wire   [7:0] grp_fu_914_p1;
wire   [15:0] grp_fu_914_p2;
wire   [7:0] grp_fu_923_p0;
wire   [7:0] grp_fu_923_p1;
wire   [15:0] grp_fu_923_p2;
reg    grp_fu_827_ce;
reg    grp_fu_835_ce;
reg    grp_fu_843_ce;
reg   [5:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire   [15:0] grp_fu_827_p00;
wire   [16:0] grp_fu_827_p20;
wire   [15:0] grp_fu_835_p00;
wire   [16:0] grp_fu_835_p20;
wire   [15:0] grp_fu_843_p00;
wire   [16:0] grp_fu_843_p20;
wire   [15:0] grp_fu_851_p00;
wire   [16:0] grp_fu_851_p20;
wire   [15:0] grp_fu_860_p00;
wire   [16:0] grp_fu_860_p20;
wire   [15:0] grp_fu_869_p00;
wire   [15:0] grp_fu_878_p00;
wire   [16:0] grp_fu_878_p20;
wire   [15:0] grp_fu_887_p00;
wire   [16:0] grp_fu_887_p20;
wire   [15:0] grp_fu_896_p00;
wire   [15:0] grp_fu_905_p00;
wire   [15:0] grp_fu_914_p00;
wire   [16:0] grp_fu_914_p20;
wire   [15:0] grp_fu_923_p00;
wire   [16:0] grp_fu_923_p20;
wire   [15:0] mul_ln47_10_fu_329_p00;
wire   [15:0] mul_ln47_12_fu_342_p00;
wire   [15:0] mul_ln47_14_fu_489_p00;
wire   [15:0] mul_ln47_5_fu_476_p00;
wire   [15:0] mul_ln47_fu_429_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_rst_reg_2 = 1'b1;
#0 ap_rst_reg_1 = 1'b1;
#0 ap_rst_n_inv = 1'b1;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 6'd1;
#0 p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_3 = 8'd0;
#0 p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_2 = 8'd0;
#0 p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_1 = 8'd0;
#0 p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_0 = 8'd0;
#0 p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_3 = 8'd0;
#0 p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_2 = 8'd0;
#0 p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_1 = 8'd0;
#0 p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_0 = 8'd0;
#0 p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_3 = 8'd0;
#0 p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_2 = 8'd0;
#0 p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_1 = 8'd0;
#0 p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_0 = 8'd0;
#0 p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_3 = 8'd0;
#0 p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_2 = 8'd0;
#0 p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_1 = 8'd0;
#0 p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_0 = 8'd0;
#0 p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_3 = 8'd0;
#0 p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_2 = 8'd0;
#0 p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_1 = 8'd0;
#0 p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_0 = 8'd0;
end

GaussianFilter_CTRL_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
CTRL_s_axi_U(
    .AWVALID(s_axi_CTRL_AWVALID),
    .AWREADY(s_axi_CTRL_AWREADY),
    .AWADDR(s_axi_CTRL_AWADDR),
    .WVALID(s_axi_CTRL_WVALID),
    .WREADY(s_axi_CTRL_WREADY),
    .WDATA(s_axi_CTRL_WDATA),
    .WSTRB(s_axi_CTRL_WSTRB),
    .ARVALID(s_axi_CTRL_ARVALID),
    .ARREADY(s_axi_CTRL_ARREADY),
    .ARADDR(s_axi_CTRL_ARADDR),
    .RVALID(s_axi_CTRL_RVALID),
    .RREADY(s_axi_CTRL_RREADY),
    .RDATA(s_axi_CTRL_RDATA),
    .RRESP(s_axi_CTRL_RRESP),
    .BVALID(s_axi_CTRL_BVALID),
    .BREADY(s_axi_CTRL_BREADY),
    .BRESP(s_axi_CTRL_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_continue(ap_continue),
    .ap_idle(ap_idle),
    .ap_return(ap_return),
    .data_in_0(data_in_0),
    .data_in_1(data_in_1),
    .data_in_2(data_in_2),
    .data_in_3(data_in_3),
    .data_in_4(data_in_4)
);

GaussianFilter_mul_8ns_9ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 16 ))
mul_8ns_9ns_16_1_1_U1(
    .din0(mul_ln47_10_fu_329_p0),
    .din1(mul_ln47_10_fu_329_p1),
    .dout(mul_ln47_10_fu_329_p2)
);

GaussianFilter_mul_8ns_9ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 16 ))
mul_8ns_9ns_16_1_1_U2(
    .din0(mul_ln47_12_fu_342_p0),
    .din1(mul_ln47_12_fu_342_p1),
    .dout(mul_ln47_12_fu_342_p2)
);

GaussianFilter_mul_8ns_9ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 16 ))
mul_8ns_9ns_16_1_1_U3(
    .din0(mul_ln47_fu_429_p0),
    .din1(mul_ln47_fu_429_p1),
    .dout(mul_ln47_fu_429_p2)
);

GaussianFilter_mul_8ns_9ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 16 ))
mul_8ns_9ns_16_1_1_U4(
    .din0(mul_ln47_5_fu_476_p0),
    .din1(mul_ln47_5_fu_476_p1),
    .dout(mul_ln47_5_fu_476_p2)
);

GaussianFilter_mul_8ns_9ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 16 ))
mul_8ns_9ns_16_1_1_U5(
    .din0(mul_ln47_14_fu_489_p0),
    .din1(mul_ln47_14_fu_489_p1),
    .dout(mul_ln47_14_fu_489_p2)
);

GaussianFilter_mac_muladd_8ns_8ns_16ns_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_8ns_16ns_17_4_1_U6(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_827_p0),
    .din1(grp_fu_827_p1),
    .din2(grp_fu_827_p2),
    .ce(grp_fu_827_ce),
    .dout(grp_fu_827_p3)
);

GaussianFilter_mac_muladd_8ns_8ns_16ns_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_8ns_16ns_17_4_1_U7(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_835_p0),
    .din1(grp_fu_835_p1),
    .din2(grp_fu_835_p2),
    .ce(grp_fu_835_ce),
    .dout(grp_fu_835_p3)
);

GaussianFilter_mac_muladd_8ns_8ns_16ns_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_8ns_16ns_17_4_1_U8(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_843_p0),
    .din1(grp_fu_843_p1),
    .din2(grp_fu_843_p2),
    .ce(grp_fu_843_ce),
    .dout(grp_fu_843_p3)
);

GaussianFilter_mac_muladd_8ns_8ns_16ns_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_8ns_16ns_17_4_1_U9(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_851_p0),
    .din1(grp_fu_851_p1),
    .din2(grp_fu_851_p2),
    .ce(1'b1),
    .dout(grp_fu_851_p3)
);

GaussianFilter_mac_muladd_8ns_8ns_16ns_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_8ns_16ns_17_4_1_U10(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_860_p0),
    .din1(grp_fu_860_p1),
    .din2(grp_fu_860_p2),
    .ce(1'b1),
    .dout(grp_fu_860_p3)
);

GaussianFilter_mac_muladd_8ns_8ns_17ns_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_8ns_17ns_17_4_1_U11(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_869_p0),
    .din1(grp_fu_869_p1),
    .din2(grp_fu_835_p3),
    .ce(1'b1),
    .dout(grp_fu_869_p3)
);

GaussianFilter_mac_muladd_8ns_8ns_16ns_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_8ns_16ns_17_4_1_U12(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_878_p0),
    .din1(grp_fu_878_p1),
    .din2(grp_fu_878_p2),
    .ce(1'b1),
    .dout(grp_fu_878_p3)
);

GaussianFilter_mac_muladd_8ns_8ns_16ns_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_8ns_16ns_17_4_1_U13(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_887_p0),
    .din1(grp_fu_887_p1),
    .din2(grp_fu_887_p2),
    .ce(1'b1),
    .dout(grp_fu_887_p3)
);

GaussianFilter_mac_muladd_8ns_8ns_17ns_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_8ns_17ns_17_4_1_U14(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_896_p0),
    .din1(grp_fu_896_p1),
    .din2(grp_fu_827_p3),
    .ce(1'b1),
    .dout(grp_fu_896_p3)
);

GaussianFilter_mac_muladd_8ns_8ns_17ns_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_8ns_17ns_17_4_1_U15(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_905_p0),
    .din1(grp_fu_905_p1),
    .din2(grp_fu_843_p3),
    .ce(1'b1),
    .dout(grp_fu_905_p3)
);

GaussianFilter_mac_muladd_8ns_8ns_16ns_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_8ns_16ns_17_4_1_U16(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_914_p0),
    .din1(grp_fu_914_p1),
    .din2(grp_fu_914_p2),
    .ce(1'b1),
    .dout(grp_fu_914_p3)
);

GaussianFilter_mac_muladd_8ns_8ns_16ns_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_8ns_16ns_17_4_1_U17(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_923_p0),
    .din1(grp_fu_923_p1),
    .din2(grp_fu_923_p2),
    .ce(1'b1),
    .dout(grp_fu_923_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state6)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    ap_rst_n_inv <= ap_rst_reg_1;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_1 <= ap_rst_reg_2;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_2 <= ~ap_rst_n;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        add_ln93_15_reg_1126 <= add_ln93_15_fu_758_p2;
        add_ln93_21_reg_1131 <= add_ln93_21_fu_783_p2;
        add_ln93_4_reg_1116 <= add_ln93_4_fu_722_p2;
        add_ln93_9_reg_1121 <= add_ln93_9_fu_746_p2;
        p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_3 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_2_load_reg_969;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        data_in_0_read_reg_1038 <= data_in_0;
        data_in_4_read_reg_1032 <= data_in_4;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        data_in_1_read_reg_1065 <= data_in_1;
        data_in_3_read_reg_1059 <= data_in_3;
        p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_0 <= data_in_0_read_reg_1038;
        p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_1 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_0;
        p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_0 <= data_in_1;
        p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_0 <= data_in_3;
        p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_0 <= data_in_4_read_reg_1032;
        p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_1 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_2 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_1;
        p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_2_load_reg_963 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_2;
        p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_3 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_2;
        p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_1 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_0;
        p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_2 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_1;
        p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_2_load_reg_969 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_2;
        p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_0 <= data_in_2;
        p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_2 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_1_load_reg_942;
        p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_3 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_2;
        p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_3_load_reg_975 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_3;
        p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_2 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_1;
        p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_2_load_reg_981 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_2;
        p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_3 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_1 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_0;
        p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_1_load_reg_937 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_1;
        p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_2 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_1;
        p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_3 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_2;
        p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_3_load_reg_932 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_3;
        p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_1 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_0;
        p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_1_load_reg_942 <= p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | ((1'b1 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1)))) begin
        grp_fu_827_ce = 1'b0;
    end else begin
        grp_fu_827_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | ((1'b1 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1)))) begin
        grp_fu_835_ce = 1'b0;
    end else begin
        grp_fu_835_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | ((1'b1 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1)))) begin
        grp_fu_843_ce = 1'b0;
    end else begin
        grp_fu_843_ce = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln47_1_fu_596_p2 = (zext_ln47_10_fu_581_p1 + zext_ln47_18_fu_592_p1);

assign add_ln47_2_fu_628_p2 = (zext_ln47_30_fu_613_p1 + zext_ln47_38_fu_624_p1);

assign add_ln47_3_fu_662_p2 = (zext_ln47_42_fu_646_p1 + zext_ln47_46_fu_658_p1);

assign add_ln47_4_fu_694_p2 = (zext_ln47_49_fu_679_p1 + zext_ln47_50_fu_690_p1);

assign add_ln47_5_fu_374_p2 = (zext_ln47_51_fu_359_p1 + zext_ln47_52_fu_370_p1);

assign add_ln47_6_fu_523_p2 = (zext_ln47_53_fu_507_p1 + zext_ln47_54_fu_519_p1);

assign add_ln47_7_fu_555_p2 = (zext_ln47_55_fu_540_p1 + zext_ln47_56_fu_551_p1);

assign add_ln47_fu_463_p2 = (zext_ln47_2_fu_447_p1 + zext_ln47_6_fu_459_p1);

assign add_ln93_10_fu_795_p2 = (zext_ln93_6_fu_792_p1 + zext_ln93_3_fu_789_p1);

assign add_ln93_15_fu_758_p2 = (zext_ln93_9_fu_755_p1 + zext_ln93_8_fu_752_p1);

assign add_ln93_1_fu_704_p2 = (grp_fu_887_p3 + zext_ln47_11_fu_634_p1);

assign add_ln93_20_fu_773_p2 = (zext_ln93_13_fu_770_p1 + zext_ln93_12_fu_767_p1);

assign add_ln93_21_fu_783_p2 = (zext_ln93_14_fu_779_p1 + zext_ln93_11_fu_764_p1);

assign add_ln93_22_fu_811_p2 = (zext_ln93_15_fu_808_p1 + zext_ln93_10_fu_805_p1);

assign add_ln93_23_fu_817_p2 = (add_ln93_22_fu_811_p2 + zext_ln93_7_fu_801_p1);

assign add_ln93_3_fu_713_p2 = (grp_fu_860_p3 + zext_ln47_31_fu_700_p1);

assign add_ln93_4_fu_722_p2 = (zext_ln93_2_fu_718_p1 + zext_ln93_1_fu_709_p1);

assign add_ln93_6_fu_728_p2 = (grp_fu_851_p3 + zext_ln47_7_fu_602_p1);

assign add_ln93_8_fu_737_p2 = (grp_fu_878_p3 + zext_ln47_19_fu_668_p1);

assign add_ln93_9_fu_746_p2 = (zext_ln93_5_fu_742_p1 + zext_ln93_4_fu_733_p1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign ap_return = add_ln93_23_fu_817_p2;

assign grp_fu_827_p0 = grp_fu_827_p00;

assign grp_fu_827_p00 = p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_0;

assign grp_fu_827_p1 = 16'd174;

assign grp_fu_827_p2 = grp_fu_827_p20;

assign grp_fu_827_p20 = add_ln47_5_fu_374_p2;

assign grp_fu_835_p0 = grp_fu_835_p00;

assign grp_fu_835_p00 = p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_2;

assign grp_fu_835_p1 = 16'd174;

assign grp_fu_835_p2 = grp_fu_835_p20;

assign grp_fu_835_p20 = mul_ln47_10_fu_329_p2;

assign grp_fu_843_p0 = grp_fu_843_p00;

assign grp_fu_843_p00 = p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_0;

assign grp_fu_843_p1 = 16'd170;

assign grp_fu_843_p2 = grp_fu_843_p20;

assign grp_fu_843_p20 = mul_ln47_12_fu_342_p2;

assign grp_fu_851_p0 = grp_fu_851_p00;

assign grp_fu_851_p00 = p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_1;

assign grp_fu_851_p1 = 16'd164;

assign grp_fu_851_p2 = grp_fu_851_p20;

assign grp_fu_851_p20 = add_ln47_fu_463_p2;

assign grp_fu_860_p0 = grp_fu_860_p00;

assign grp_fu_860_p00 = p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_3;

assign grp_fu_860_p1 = 16'd151;

assign grp_fu_860_p2 = grp_fu_860_p20;

assign grp_fu_860_p20 = mul_ln47_14_fu_489_p2;

assign grp_fu_869_p0 = grp_fu_869_p00;

assign grp_fu_869_p00 = p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_0;

assign grp_fu_869_p1 = 16'd170;

assign grp_fu_878_p0 = grp_fu_878_p00;

assign grp_fu_878_p00 = p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_1;

assign grp_fu_878_p1 = 16'd174;

assign grp_fu_878_p2 = grp_fu_878_p20;

assign grp_fu_878_p20 = mul_ln47_5_fu_476_p2;

assign grp_fu_887_p0 = grp_fu_887_p00;

assign grp_fu_887_p00 = data_in_2;

assign grp_fu_887_p1 = 16'd164;

assign grp_fu_887_p2 = grp_fu_887_p20;

assign grp_fu_887_p20 = mul_ln47_fu_429_p2;

assign grp_fu_896_p0 = grp_fu_896_p00;

assign grp_fu_896_p00 = p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_1_load_reg_937;

assign grp_fu_896_p1 = 16'd177;

assign grp_fu_905_p0 = grp_fu_905_p00;

assign grp_fu_905_p00 = p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_2;

assign grp_fu_905_p1 = 16'd170;

assign grp_fu_914_p0 = grp_fu_914_p00;

assign grp_fu_914_p00 = p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_1;

assign grp_fu_914_p1 = 16'd164;

assign grp_fu_914_p2 = grp_fu_914_p20;

assign grp_fu_914_p20 = add_ln47_6_fu_523_p2;

assign grp_fu_923_p0 = grp_fu_923_p00;

assign grp_fu_923_p00 = p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_3;

assign grp_fu_923_p1 = 16'd151;

assign grp_fu_923_p2 = grp_fu_923_p20;

assign grp_fu_923_p20 = add_ln47_7_fu_555_p2;

assign mul_ln47_10_fu_329_p0 = mul_ln47_10_fu_329_p00;

assign mul_ln47_10_fu_329_p00 = p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_2_3_load_reg_932;

assign mul_ln47_10_fu_329_p1 = 16'd164;

assign mul_ln47_12_fu_342_p0 = mul_ln47_12_fu_342_p00;

assign mul_ln47_12_fu_342_p00 = p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_1_load_reg_942;

assign mul_ln47_12_fu_342_p1 = 16'd174;

assign mul_ln47_14_fu_489_p0 = mul_ln47_14_fu_489_p00;

assign mul_ln47_14_fu_489_p00 = data_in_4_read_reg_1032;

assign mul_ln47_14_fu_489_p1 = 16'd151;

assign mul_ln47_5_fu_476_p0 = mul_ln47_5_fu_476_p00;

assign mul_ln47_5_fu_476_p00 = p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_2_load_reg_969;

assign mul_ln47_5_fu_476_p1 = 16'd170;

assign mul_ln47_fu_429_p0 = mul_ln47_fu_429_p00;

assign mul_ln47_fu_429_p00 = data_in_0_read_reg_1038;

assign mul_ln47_fu_429_p1 = 16'd151;

assign tmp_10_fu_352_p3 = {{p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_3_load_reg_975}, {7'd0}};

assign tmp_11_fu_363_p3 = {{p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_3_3_load_reg_975}, {5'd0}};

assign tmp_12_fu_499_p3 = {{p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_0}, {7'd0}};

assign tmp_13_fu_511_p3 = {{p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_0}, {5'd0}};

assign tmp_14_fu_533_p3 = {{p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_2_load_reg_981}, {7'd0}};

assign tmp_15_fu_544_p3 = {{p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_4_2_load_reg_981}, {5'd0}};

assign tmp_1_fu_451_p3 = {{p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_0}, {5'd0}};

assign tmp_2_fu_574_p3 = {{p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_2_load_reg_963}, {7'd0}};

assign tmp_3_fu_585_p3 = {{p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_2_load_reg_963}, {5'd0}};

assign tmp_4_fu_606_p3 = {{data_in_1_read_reg_1065}, {7'd0}};

assign tmp_5_fu_617_p3 = {{data_in_1_read_reg_1065}, {5'd0}};

assign tmp_6_fu_638_p3 = {{p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_3}, {7'd0}};

assign tmp_7_fu_650_p3 = {{p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_1_3}, {5'd0}};

assign tmp_8_fu_672_p3 = {{data_in_3_read_reg_1059}, {7'd0}};

assign tmp_9_fu_683_p3 = {{data_in_3_read_reg_1059}, {5'd0}};

assign tmp_fu_439_p3 = {{p_ZZ14GaussianFilter7ap_uintILi8EES0_S0_S0_S0_E13data_in_array_0_0}, {7'd0}};

assign zext_ln47_10_fu_581_p1 = tmp_2_fu_574_p3;

assign zext_ln47_11_fu_634_p1 = add_ln47_2_fu_628_p2;

assign zext_ln47_18_fu_592_p1 = tmp_3_fu_585_p3;

assign zext_ln47_19_fu_668_p1 = add_ln47_3_fu_662_p2;

assign zext_ln47_2_fu_447_p1 = tmp_fu_439_p3;

assign zext_ln47_30_fu_613_p1 = tmp_4_fu_606_p3;

assign zext_ln47_31_fu_700_p1 = add_ln47_4_fu_694_p2;

assign zext_ln47_38_fu_624_p1 = tmp_5_fu_617_p3;

assign zext_ln47_42_fu_646_p1 = tmp_6_fu_638_p3;

assign zext_ln47_46_fu_658_p1 = tmp_7_fu_650_p3;

assign zext_ln47_49_fu_679_p1 = tmp_8_fu_672_p3;

assign zext_ln47_50_fu_690_p1 = tmp_9_fu_683_p3;

assign zext_ln47_51_fu_359_p1 = tmp_10_fu_352_p3;

assign zext_ln47_52_fu_370_p1 = tmp_11_fu_363_p3;

assign zext_ln47_53_fu_507_p1 = tmp_12_fu_499_p3;

assign zext_ln47_54_fu_519_p1 = tmp_13_fu_511_p3;

assign zext_ln47_55_fu_540_p1 = tmp_14_fu_533_p3;

assign zext_ln47_56_fu_551_p1 = tmp_15_fu_544_p3;

assign zext_ln47_6_fu_459_p1 = tmp_1_fu_451_p3;

assign zext_ln47_7_fu_602_p1 = add_ln47_1_fu_596_p2;

assign zext_ln93_10_fu_805_p1 = add_ln93_15_reg_1126;

assign zext_ln93_11_fu_764_p1 = grp_fu_905_p3;

assign zext_ln93_12_fu_767_p1 = grp_fu_923_p3;

assign zext_ln93_13_fu_770_p1 = grp_fu_914_p3;

assign zext_ln93_14_fu_779_p1 = add_ln93_20_fu_773_p2;

assign zext_ln93_15_fu_808_p1 = add_ln93_21_reg_1131;

assign zext_ln93_1_fu_709_p1 = add_ln93_1_fu_704_p2;

assign zext_ln93_2_fu_718_p1 = add_ln93_3_fu_713_p2;

assign zext_ln93_3_fu_789_p1 = add_ln93_4_reg_1116;

assign zext_ln93_4_fu_733_p1 = add_ln93_6_fu_728_p2;

assign zext_ln93_5_fu_742_p1 = add_ln93_8_fu_737_p2;

assign zext_ln93_6_fu_792_p1 = add_ln93_9_reg_1121;

assign zext_ln93_7_fu_801_p1 = add_ln93_10_fu_795_p2;

assign zext_ln93_8_fu_752_p1 = grp_fu_869_p3;

assign zext_ln93_9_fu_755_p1 = grp_fu_896_p3;

endmodule //GaussianFilter
